''------------------------------------------------------------------------------
'' <auto-generated>
''     This code was generated by a tool.
''     Runtime Version:4.0.30319.42000
''
''     Changes to this file may cause incorrect behavior and will be lost if
''     the code is regenerated.
'' </auto-generated>
''------------------------------------------------------------------------------

'Option Strict Off
'Option Explicit On

'Imports B1WizardBase
'Imports SAPbobsCOM
'Imports SAPbouiCOM

'Namespace Factura_Electronica

'    Public Class EventsHandler
'        Inherits B1Event

'        Public Sub New()
'            MyBase.New
'        End Sub

'        <B1Listener(BoEventTypes.et_FORM_DATA_ADD, True)>
'        Public Overridable Function OnBeforeFormDataAdd(ByVal pVal As BusinessObjectInfo) As Boolean
'            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
'            'ADD YOUR ACTION CODE HERE ...
'            'ADD YOUR ACTION CODE HERE ...
'            form = B1Connections.theAppl.Forms.ActiveForm

'            Dim nSum As Decimal = 0.0
'            Dim nTotal1 As Decimal = 0.0
'            Dim nTotal2 As Decimal = 0.0

'            If (form.TypeEx.ToString() = "133") Then



'                Dim oMatrix As SAPbouiCOM.Matrix
'                Dim oCheck As SAPbouiCOM.CheckBox

'                oMatrix = form.Items.Item("38").Specific



'                For iContTotal As Integer = 1 To oMatrix.RowCount - 1

'                    nSum += oMatrix.Columns.Item("288").Cells.Item(iContTotal).Specific.value.ToString().Replace("QTZ", "")


'                Next


'                nTotal1 = nSum - form.Items.Item("29").Specific.value.ToString().Replace("QTZ", "")


'                If Not nTotal1 = 0 Then

'                    form.Freeze(True)

'                    oCheck = form.Items.Item("105").Specific

'                    oCheck.Checked = True

'                    form.Items.Item("103").Specific.value = nTotal1

'                    form.Items.Item("1").Click()

'                    form.Freeze(False)
'                End If


'                'form.Items.Item("29").Specific.value = "543.13"
'                'form.Items.Item("24").Specific.value = "-0.008"
'                ' form.Items.Item("42").Specific.value = "-0.04"

'                'nTotal = form.Items.Item("29").Specific.value.ToString().Replace("QTZ", "")

'                'nTotal2 = Convert.ToDecimal(543.13 - form.Items.Item("29").Specific.value.ToString().Replace("QTZ", ""))

'                'form.Items.Item("42").Specific.value = "-" & nTotal2


'                'EndGame = (nTotal2 / 543.13) * 100


'                'form.Items.Item("24").Specific.value = "-" & EndGame

'                'form.Items.Item("29").Specific.value = "543.13"
'            End If


'            Return True
'        End Function

'    End Class
'End Namespace
