'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM
Imports System.Collections.Generic

Namespace Factura_Electronica

    Public Class Button__FacPDF
        Inherits B1Item

        Public Sub New()
            MyBase.New()
            FormType = "133"
            ItemUID = "btnPDF"
        End Sub

        <B1Listener(BoEventTypes.et_CLICK, False)>
        Public Overridable Sub OnAfterClick(ByVal pVal As ItemEvent)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("btnPDF")
            Dim button As Button = CType(item.Specific, Button)
            'ADD YOUR ACTION CODE HERE ...
            Dim Serie As String
            Dim Numero As String

            Try
                Serie = form.Items.Item("88").Specific.value
                Numero = form.Items.Item("8").Specific.value
                Mostrar_PDF("133", Serie, Numero)
            Catch ex As Exception
                B1Connections.theAppl.SetStatusBarMessage(ex.Message, SAPbouiCOM.BoMessageTime.bmt_Short, True)
            End Try
        End Sub
    End Class
End Namespace
