'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM
Imports InFile.net.ingface.www
Imports System.Xml
Imports System.Net
Imports System.IO
Imports System.Runtime.InteropServices
Imports System.Drawing.Printing

Namespace InFile

    Public Class Forma_Factura
        Inherits B1Event

        Public Sub New()
            MyBase.New
        End Sub
        <DllImport("shell32")>
        Public Shared Function ShellExecute(ByVal hWnd As IntPtr,
                                        ByVal lpOperation As String,
                                        ByVal lpFile As String,
                                        ByVal lpParameters As String,
                                        ByVal lpDirectory As String,
                                        ByVal nShowCmd As Integer) As IntPtr
        End Function
        Private Function quitarSaltosLinea(ByVal texto As String,
                      caracterReemplazar As String) As String
            quitarSaltosLinea = Replace(Replace(texto, Chr(10),
                caracterReemplazar), Chr(13), caracterReemplazar)
        End Function
        <B1Listener(BoEventTypes.et_FORM_DATA_ADD, False)>
        Public Overridable Sub OnAfterFormDataAdd(ByVal pVal As BusinessObjectInfo)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim oRecordSetH As SAPbobsCOM.Recordset
            Dim oRecordSetCnfgFace As SAPbobsCOM.Recordset
            Dim oRecordSetCnfSerie As SAPbobsCOM.Recordset
            Dim oRecordSetD As SAPbobsCOM.Recordset
            Dim oRutaPdf As String = ""
            Dim sQuery As String
            Dim oXML As New XmlDocument
            Dim oXMLRet As New XmlDocument
            Dim oXMLInterno As New XmlDocument
            Dim xmlNodeRdr As XmlNodeReader
            Dim sXML As String
            Dim sUrl As String
            Dim dsGenerarGuia As New DataSet()
            Dim HttpReq As HttpWebRequest
            Dim nCae As String = ""
            Dim nFac As String = ""
            Dim nSer As String = ""
            Dim nMen As String = ""
            Dim UrlPDF As String = ""
            Dim nVal As String = ""
            Dim oRecordSetUpdate As SAPbobsCOM.Recordset
            Dim oRecordSetDepartamento As SAPbobsCOM.Recordset
            Dim oRecordSetDepartamentoV As SAPbobsCOM.Recordset
            Dim oRecordSetDireccion As SAPbobsCOM.Recordset
            Dim oRecordSetImporteDesc As SAPbobsCOM.Recordset
            Dim oRecordSetMunicipio As SAPbobsCOM.Recordset
            Dim oRecordSetMunicipioV As SAPbobsCOM.Recordset
            Dim oRecordSetNitV As SAPbobsCOM.Recordset
            Dim oRecordSetRazonS As SAPbobsCOM.Recordset
            Dim oRecordSetTipoCambio As SAPbobsCOM.Recordset
            'ADD YOUR ACTION CODE HERE ...
            form = B1Connections.theAppl.Forms.ActiveForm


            Try

                oRecordSetCnfgFace = Nothing
                oRecordSetCnfgFace = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "select * from [@CONFGFACE] "
                oRecordSetCnfgFace.DoQuery(sQuery)
                oRecordSetCnfgFace.MoveFirst()

                If form.TypeEx = "133" Then



                    oRecordSetH = Nothing
                    oRecordSetH = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                    sQuery = "Select T1.*,T0.""E_mail"",T0.""U_NIT"",T0.""Phone1"" From OINV T1 inner join OCRD T0 On T0.""CardCode"" = T1.""CardCode"" Where T1.""DocNum"" = " & form.Items.Item("8").Specific.value
                    oRecordSetH.DoQuery(sQuery)
                    If Not String.IsNullOrEmpty(oRecordSetH.Fields.Item("CardCode").Value) Then

                        oRecordSetCnfSerie = Nothing
                        oRecordSetCnfSerie = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "Select * from [@CNFSERIE] where ""U_Serie"" = '" & oRecordSetH.Fields.Item("Series").Value & "' and ""U_Document"" = '" & oRecordSetH.Fields.Item("ObjType").Value & "' "
                        oRecordSetCnfSerie.DoQuery(sQuery)
                        oRecordSetCnfSerie.MoveFirst()



                        If Not String.IsNullOrEmpty(oRecordSetCnfSerie.Fields.Item("Object").Value) Then

                            oRecordSetTipoCambio = Nothing
                            oRecordSetTipoCambio = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)

                            If oRecordSetCnfgFace.Fields.Item("U_Tipo").Value.ToString() = "1" Then
                                sQuery = "select ""Rate"" from ORTT where ""Currency"" = 'USD' and ""RateDate"" = CONVERT(VARCHAR(10),GETDATE(),111) "
                            ElseIf oRecordSetCnfgFace.Fields.Item("U_Tipo").Value.ToString() = "2" Then
                                sQuery = "select ""Rate"" from ORTT where ""Currency"" = 'USD' and ""RateDate"" = CURRENT_DATE"
                            End If

                            oRecordSetTipoCambio.DoQuery(sQuery)
                            oRecordSetTipoCambio.MoveFirst()


                            sXML = "<?xml version=""1.0""?>"
                            sXML &= "<S:Envelope xmlns:S=""http://schemas.xmlsoap.org/soap/envelope/"">"
                            sXML &= "   <S:Body>"
                            sXML &= "       <ns2:registrarDte xmlns:ns2=""http://listener.ingface.com/"">"
                            sXML &= "          <dte>"
                            sXML &= "               <clave>" & oRecordSetCnfgFace.Fields.Item("U_Token").Value.ToString.Trim() & "</clave>"
                            sXML &= "               <dte>"
                            sXML &= "                   <codigoEstablecimiento>" & oRecordSetCnfSerie.Fields.Item("U_Establec").Value.ToString.Trim() & "</codigoEstablecimiento>"

                            If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                sXML &= "                   <codigoMoneda>GTQ</codigoMoneda>"
                            ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                                sXML &= "                   <codigoMoneda>USD</codigoMoneda>"
                            End If


                            If Not String.IsNullOrEmpty(oRecordSetH.Fields.Item("E_mail").Value) Then
                                sXML &= "                   <correoComprador>" & oRecordSetH.Fields.Item("E_mail").Value & "</correoComprador>"
                            Else
                                sXML &= "                   <correoComprador>N/A</correoComprador>"
                            End If



                            oRecordSetDepartamento = Nothing
                            oRecordSetDepartamento = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = " Select T3.""Name"" from OCST T3 where T3.""Code"" in (select T0.""State"" from CRD1 T0 where T0.""CardCode"" = '" & oRecordSetH.Fields.Item("CardCode").Value & "' "
                            sQuery &= " And T0.""AdresType"" = 'S' and T0.""Address"" in (select ""ShipToDef"" from OCRD T1 where T1.""CardCode"" = T0.""CardCode""))"
                            oRecordSetDepartamento.DoQuery(sQuery)
                            oRecordSetDepartamento.MoveFirst()

                            If Not String.IsNullOrEmpty(oRecordSetDepartamento.Fields.Item(0).Value) Then
                                sXML &= "                   <departamentoComprador>" & oRecordSetDepartamento.Fields.Item(0).Value & "</departamentoComprador>"
                            Else
                                sXML &= "                   <departamentoComprador>N/A</departamentoComprador>"
                            End If

                            oRecordSetDepartamentoV = Nothing
                            oRecordSetDepartamentoV = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = "select T3.""Name"" from OCST T3 where T3.""Code"" in(select ""State"" from OADM)"
                            oRecordSetDepartamentoV.DoQuery(sQuery)
                            oRecordSetDepartamentoV.MoveFirst()

                            If Not String.IsNullOrEmpty(oRecordSetDepartamentoV.Fields.Item(0).Value) Then
                                sXML &= "                   <departamentoVendedor>" & oRecordSetDepartamentoV.Fields.Item(0).Value & "</departamentoVendedor>"
                            End If

                            sXML &= "                   <descripcionOtroImpuesto>N/A</descripcionOtroImpuesto>"


                            oRecordSetD = Nothing
                            oRecordSetD = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = "Select * From INV1 T0 Where T0.""DocEntry"" = " & oRecordSetH.Fields.Item("DocEntry").Value
                            oRecordSetD.DoQuery(sQuery)
                            For iCont As Integer = 0 To oRecordSetD.RecordCount - 1


                                If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                    sXML &= "                   <detalleDte>"

                                    If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                        sXML &= "                      <cantidad>" & oRecordSetD.Fields.Item("Quantity").Value & "</cantidad>"
                                    ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                        sXML &= "                      <cantidad>1</cantidad>"
                                    End If

                                    If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                        sXML &= "                       <codigoProducto>" & oRecordSetD.Fields.Item("ItemCode").Value & "</codigoProducto>"
                                    ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                        sXML &= "                      <cantidad>N/A</cantidad>"
                                    End If


                                    sXML &= "                       <descripcionProducto>" & oRecordSetD.Fields.Item("Dscription").Value & "</descripcionProducto>"

                                    If oRecordSetD.Fields.Item("TaxCode").Value = "IVA" Then
                                        sXML &= "                       <detalleImpuestosIva>" & oRecordSetD.Fields.Item("VatSum").Value & "</detalleImpuestosIva>"
                                    ElseIf oRecordSetD.Fields.Item("TaxCode").Value = "EXE" Then
                                        sXML &= "                       <detalleImpuestosIva>0.000</detalleImpuestosIva>"
                                    End If

                                    If oRecordSetD.Fields.Item("TaxCode").Value = "IVA" Then
                                        sXML &= "                       <importeExento>0.000</importeExento>"
                                    ElseIf oRecordSetD.Fields.Item("TaxCode").Value = "EXE" Then
                                        sXML &= "                       <importeExento>" & oRecordSetH.Fields.Item("DocTotal").Value & "</importeExento>"
                                    End If



                                    sXML &= "                       <importeNetoGravado>" & oRecordSetD.Fields.Item("PriceAfVAT").Value & "</importeNetoGravado>"
                                    sXML &= "                       <importeOtrosImpuestos>0.000</importeOtrosImpuestos>"
                                    sXML &= "                       <importeTotalOperacion>" & oRecordSetD.Fields.Item("GTotal").Value & "</importeTotalOperacion>"
                                    sXML &= "                       <montoBruto>" & oRecordSetD.Fields.Item("LineTotal").Value & "</montoBruto>"
                                    sXML &= "                       <montoDescuento>" & ((oRecordSetD.Fields.Item("PriceBefDi").Value * oRecordSetD.Fields.Item("Quantity").Value) - oRecordSetD.Fields.Item("LineTotal").Value) & "</montoDescuento>"

                                    sXML &= "                       <personalizado_01>N/A</personalizado_01>"
                                    sXML &= "                       <personalizado_02>N/A</personalizado_02>"
                                    sXML &= "                       <personalizado_03>N/A</personalizado_03>"
                                    sXML &= "                       <personalizado_04>N/A</personalizado_04>"
                                    sXML &= "                       <personalizado_05>N/A</personalizado_05>"
                                    sXML &= "                       <personalizado_06>N/A</personalizado_06>"
                                    'Pendiente
                                    sXML &= "                       <precioUnitario>" & oRecordSetD.Fields.Item("PriceBefDi").Value & "</precioUnitario>"



                                ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then

                                    '''''''''''''''''''''''''''''
                                    sXML &= "                   <detalleDte>"

                                    If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                        sXML &= "                      <cantidad>" & oRecordSetD.Fields.Item("Quantity").Value & "</cantidad>"
                                    ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                        sXML &= "                      <cantidad>1</cantidad>"
                                    End If

                                    If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                        sXML &= "                       <codigoProducto>" & oRecordSetD.Fields.Item("ItemCode").Value & "</codigoProducto>"
                                    ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                        sXML &= "                      <cantidad>N/A</cantidad>"
                                    End If

                                    sXML &= "                       <descripcionProducto>" & oRecordSetD.Fields.Item("Dscription").Value & "</descripcionProducto>"

                                    If oRecordSetD.Fields.Item("TaxCode").Value = "IVA" Then
                                        sXML &= "                       <detalleImpuestosIva>" & (oRecordSetD.Fields.Item("VatSum").Value * oRecordSetTipoCambio.Fields.Item(0).Value) & "</detalleImpuestosIva>"
                                    ElseIf oRecordSetD.Fields.Item("TaxCode").Value = "EXE" Then
                                        sXML &= "                       <detalleImpuestosIva>0.000</detalleImpuestosIva>"
                                    End If

                                    If oRecordSetD.Fields.Item("TaxCode").Value = "IVA" Then
                                        sXML &= "                       <importeExento>0.000</importeExento>"
                                    ElseIf oRecordSetD.Fields.Item("TaxCode").Value = "EXE" Then
                                        sXML &= "                       <importeExento>" & (oRecordSetH.Fields.Item("DocTotal").Value) & "</importeExento>"
                                    End If


                                    sXML &= "                       <importeNetoGravado>" & (oRecordSetD.Fields.Item("PriceAfVAT").Value * oRecordSetTipoCambio.Fields.Item(0).Value) & "</importeNetoGravado>"
                                    sXML &= "                       <importeOtrosImpuestos>0.000</importeOtrosImpuestos>"
                                    sXML &= "                       <importeTotalOperacion>" & (oRecordSetD.Fields.Item("GTotal").Value) & "</importeTotalOperacion>"
                                    sXML &= "                       <montoBruto>" & oRecordSetD.Fields.Item("LineTotal").Value & "</montoBruto>"
                                    sXML &= "                       <montoDescuento>" & (((oRecordSetD.Fields.Item("PriceBefDi").Value * oRecordSetTipoCambio.Fields.Item(0).Value) * oRecordSetD.Fields.Item("Quantity").Value) - oRecordSetD.Fields.Item("LineTotal").Value) & "</montoDescuento>"

                                    sXML &= "                       <personalizado_01>N/A</personalizado_01>"
                                    sXML &= "                       <personalizado_02>N/A</personalizado_02>"
                                    sXML &= "                       <personalizado_03>N/A</personalizado_03>"
                                    sXML &= "                       <personalizado_04>N/A</personalizado_04>"
                                    sXML &= "                       <personalizado_05>N/A</personalizado_05>"
                                    sXML &= "                       <personalizado_06>N/A</personalizado_06>"
                                    'Pendiente
                                    sXML &= "                       <precioUnitario>" & (oRecordSetD.Fields.Item("PriceBefDi").Value * oRecordSetTipoCambio.Fields.Item(0).Value) & "</precioUnitario>"



                                End If

                                If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                    sXML &= "                       <tipoProducto>B</tipoProducto>"
                                ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                    sXML &= "                       <tipoProducto>S</tipoProducto>"
                                End If
                                'Pendiente
                                If String.IsNullOrEmpty(oRecordSetD.Fields.Item("unitMsr").Value.ToString()) Then
                                    sXML &= "                       <unidadMedida>N/A</unidadMedida>"
                                Else
                                    sXML &= "                       <unidadMedida>" & oRecordSetD.Fields.Item("UomCode").Value.ToString().Trim().Substring(0, 3) & "</unidadMedida>"
                                End If

                                sXML &= "                   </detalleDte>"

                                oRecordSetD.MoveNext()



                            Next



                            If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                sXML &= "                   <detalleImpuestosIva>" & oRecordSetH.Fields.Item("VatSum").Value & "</detalleImpuestosIva>"
                            ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                                sXML &= "                   <detalleImpuestosIva>" & (oRecordSetH.Fields.Item("VatSum").Value * oRecordSetTipoCambio.Fields.Item(0).Value) & "</detalleImpuestosIva>"
                            End If

                            If String.IsNullOrEmpty(oRecordSetH.Fields.Item("Address").Value) Then
                                sXML &= "                   <direccionComercialComprador>N/A</direccionComercialComprador>"
                            Else
                                sXML &= "                   <direccionComercialComprador>" & quitarSaltosLinea(oRecordSetH.Fields.Item("Address").Value, " ") & "</direccionComercialComprador>"
                            End If



                            oRecordSetDireccion = Nothing
                            oRecordSetDireccion = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = "Select T0.""Street"" from ADM1 T0"
                            oRecordSetDireccion.DoQuery(sQuery)
                            oRecordSetDireccion.MoveFirst()

                            sXML &= "                   <direccionComercialVendedor>" & oRecordSetDireccion.Fields.Item(0).Value & "</direccionComercialVendedor>"
                            sXML &= "                   <estadoDocumento>ACTIVO</estadoDocumento>"

                            sXML &= "                   <fechaAnulacion>" & CDate(oRecordSetH.Fields.Item("TaxDate").Value).ToString("yyyy-MM-dd") & "</fechaAnulacion>"
                            sXML &= "                   <fechaDocumento>" & CDate(oRecordSetH.Fields.Item("TaxDate").Value).ToString("yyyy-MM-dd") & "</fechaDocumento>"
                            sXML &= "                   <fechaResolucion>" & CDate(oRecordSetCnfSerie.Fields.Item("U_Fecha").Value).ToString("yyyy-MM-dd") & "</fechaResolucion>"

                            sXML &= "                   <idDispositivo>" & oRecordSetCnfSerie.Fields.Item("U_Disposi").Value & "</idDispositivo>"

                            If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                sXML &= "                   <importeBruto>" & (oRecordSetH.Fields.Item("DocTotal").Value - oRecordSetH.Fields.Item("VatSum").Value) & "</importeBruto>"
                            ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                                sXML &= "                   <importeBruto>" & (oRecordSetH.Fields.Item("DocTotal").Value - oRecordSetH.Fields.Item("VatSum").Value) & "</importeBruto>"
                            End If



                            oRecordSetImporteDesc = Nothing
                            oRecordSetImporteDesc = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)

                            If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                sQuery = "select sum((""PriceBefDi"" * ""Quantity"") - ""LineTotal"") from INV1 where ""DocEntry"" = " & oRecordSetH.Fields.Item("DocEntry").Value
                            ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                                sQuery = "select sum((""PriceBefDi"" * 7.5) * ""Quantity"") - (""LineTotal"") from INV1 where ""DocEntry"" = " & oRecordSetH.Fields.Item("DocEntry").Value & " group by ""LineTotal"" "
                            End If

                            oRecordSetImporteDesc.DoQuery(sQuery)
                            oRecordSetImporteDesc.MoveFirst()

                            sXML &= "                   <importeDescuento>" & oRecordSetImporteDesc.Fields.Item(0).Value & "</importeDescuento>"


                            If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                sXML &= "                   <importeNetoGravado>" & oRecordSetH.Fields.Item("DocTotal").Value & "</importeNetoGravado>"
                            ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                                sXML &= "                   <importeNetoGravado>" & oRecordSetH.Fields.Item("DocTotal").Value & "</importeNetoGravado>"
                            End If

                            sXML &= "                   <importeOtrosImpuestos>0.0</importeOtrosImpuestos>"
                            sXML &= "                   <importeTotalExento>0.0</importeTotalExento>"

                            If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                sXML &= "                   <montoTotalOperacion>" & oRecordSetH.Fields.Item("DocTotal").Value & "</montoTotalOperacion>"
                            ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                                sXML &= "                   <montoTotalOperacion>" & oRecordSetH.Fields.Item("DocTotal").Value & "</montoTotalOperacion>"
                            End If


                            oRecordSetMunicipio = Nothing
                            oRecordSetMunicipio = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = "select T0.""County"" from CRD1 T0 where T0.""CardCode"" = '" & oRecordSetH.Fields.Item("CardCode").Value & "' "
                            sQuery &= " And T0.""AdresType"" = 'S' and T0.""Address"" in (select ""ShipToDef"" from OCRD T1 where T1.""CardCode"" = T0.""CardCode"" ) "
                            oRecordSetMunicipio.DoQuery(sQuery)
                            oRecordSetMunicipio.MoveFirst()

                            If Not String.IsNullOrEmpty(oRecordSetMunicipio.Fields.Item(0).Value) Then
                                sXML &= "                   <municipioComprador>" & oRecordSetMunicipio.Fields.Item(0).Value & "</municipioComprador>"
                            Else
                                sXML &= "                   <municipioComprador>N/A</municipioComprador>"
                            End If

                            oRecordSetMunicipioV = Nothing
                            oRecordSetMunicipioV = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = "Select ""County"" from ADM1"
                            oRecordSetMunicipioV.DoQuery(sQuery)
                            oRecordSetMunicipioV.MoveFirst()

                            sXML &= "                   <municipioVendedor>" & oRecordSetMunicipioV.Fields.Item(0).Value.ToString.Trim() & "</municipioVendedor>"
                            sXML &= "                   <nitComprador>" & oRecordSetH.Fields.Item("U_NIT").Value.ToString().Replace("-", "").Trim().TrimEnd().TrimStart() & "</nitComprador>"
                            sXML &= "                   <nitGFACE>" & oRecordSetCnfgFace.Fields.Item("U_NitFace").Value.ToString().Replace("-", "").Trim().TrimEnd().TrimStart() & "</nitGFACE>"


                            oRecordSetNitV = Nothing
                            oRecordSetNitV = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = "Select T0.""TaxIdNum"" from OADM T0"
                            oRecordSetNitV.DoQuery(sQuery)
                            oRecordSetNitV.MoveFirst()
                            sXML &= "                   <nitVendedor>" & oRecordSetNitV.Fields.Item(0).Value.ToString().Replace("-", "").Trim().TrimEnd().TrimStart() & "</nitVendedor>"


                            sXML &= "                   <nombreComercialComprador>" & oRecordSetH.Fields.Item("CardName").Value & "</nombreComercialComprador>"

                            oRecordSetRazonS = Nothing
                            oRecordSetRazonS = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = "Select T0.""PrintHeadr"" from OADM T0"
                            oRecordSetRazonS.DoQuery(sQuery)
                            oRecordSetRazonS.MoveFirst()



                            sXML &= "                   <nombreComercialRazonSocialVendedor>" & oRecordSetRazonS.Fields.Item(0).Value & "</nombreComercialRazonSocialVendedor>"

                            sXML &= "                   <nombreCompletoVendedor>" & oRecordSetRazonS.Fields.Item(0).Value & "</nombreCompletoVendedor>"
                            sXML &= "                   <numeroDocumento>" & oRecordSetH.Fields.Item("DocNum").Value & "</numeroDocumento>"
                            sXML &= "                   <numeroResolucion>" & oRecordSetCnfSerie.Fields.Item("U_Resolu").Value & "</numeroResolucion>"
                            sXML &= "                   <observaciones>" & oRecordSetH.Fields.Item("Comments").Value & "</observaciones>"
                            sXML &= "                   <personalizado_01>N/A</personalizado_01>"
                            sXML &= "                   <personalizado_02>N/A</personalizado_02>"
                            sXML &= "                   <personalizado_03>N/A</personalizado_03>"
                            sXML &= "                   <personalizado_04>N/A</personalizado_04>"
                            sXML &= "                   <personalizado_05>N/A</personalizado_05>"
                            sXML &= "                   <personalizado_06>N/A</personalizado_06>"
                            sXML &= "                   <personalizado_07>N/A</personalizado_07>"
                            sXML &= "                   <personalizado_08>N/A</personalizado_08>"
                            sXML &= "                   <personalizado_09>N/A</personalizado_09>"
                            sXML &= "                   <personalizado_10>N/A</personalizado_10>"
                            sXML &= "                   <personalizado_11>N/A</personalizado_11>"
                            sXML &= "                   <personalizado_12>N/A</personalizado_12>"
                            sXML &= "                   <personalizado_13>N/A</personalizado_13>"
                            sXML &= "                   <personalizado_14>N/A</personalizado_14>"
                            sXML &= "                   <personalizado_15>N/A</personalizado_15>"
                            sXML &= "                   <personalizado_16>N/A</personalizado_16>"
                            sXML &= "                   <personalizado_17>N/A</personalizado_17>"
                            sXML &= "                   <personalizado_18>N/A</personalizado_18>"
                            sXML &= "                   <personalizado_19>N/A</personalizado_19>"
                            sXML &= "                   <personalizado_20>N/A</personalizado_20>"
                            'Pendiente
                            sXML &= "                   <regimen2989>1</regimen2989>"

                            If oRecordSetCnfgFace.Fields.Item("U_Regimen").Value = "1" Then
                                sXML &= "                   <regimenISR>RET_DEFINITIVA</regimenISR>"
                            Else
                                sXML &= "                   <regimenISR>NOT_RET_DEFINITIVA</regimenISR>"
                            End If


                            sXML &= "                   <serieAutorizada>" & oRecordSetCnfSerie.Fields.Item("U_SerieDoc").Value.ToString.Trim() & "</serieAutorizada>"
                            sXML &= "                   <serieDocumento>" & oRecordSetCnfSerie.Fields.Item("U_CodeSAT").Value.ToString.Trim() & "</serieDocumento>"

                            If String.IsNullOrEmpty(oRecordSetH.Fields.Item("Phone1").Value) Then
                                sXML &= "                   <telefonoComprador>N/A</telefonoComprador>"
                            Else
                                sXML &= "                   <telefonoComprador>" & oRecordSetH.Fields.Item("Phone1").Value.ToString().Trim().Replace("-", "") & "</telefonoComprador>"
                            End If



                            If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                sXML &= "                   <tipoCambio>1.0</tipoCambio>"
                            ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                                sXML &= "                   <tipoCambio>" & oRecordSetTipoCambio.Fields.Item(0).Value & "</tipoCambio>"
                            End If


                            sXML &= "                   <tipoDocumento>FACE</tipoDocumento>"
                            sXML &= "               </dte>"
                            sXML &= "               <usuario>" & oRecordSetCnfgFace.Fields.Item("U_Usuario").Value.ToString.Trim() & "</usuario>"
                            sXML &= "               <validador>False</validador>"
                            sXML &= "          </dte>"
                            sXML &= "       </ns2:registrarDte>"
                            sXML &= "   </S:Body>"
                            sXML &= "</S:Envelope>"

                            oXML.LoadXml(sXML)
                            oXML.Save(oRecordSetCnfgFace.Fields.Item("U_RutaXML").Value.ToString() & "\ Factura # " & oRecordSetH.Fields.Item("DocNum").Value & ".XML")
                            '                        sUrl = "https://www.ingface.net/listener/ingface?wsdl"
                            sUrl = oRecordSetCnfgFace.Fields.Item("U_UrlWeb").Value.ToString.Trim()
                            oXMLRet = PostXMLTransaction(sUrl, oXML, "")
                            oXMLRet.Save(oRecordSetCnfgFace.Fields.Item("U_RutaXML").Value.ToString() & "\ Factura # " & oRecordSetH.Fields.Item("DocNum").Value & "_Respuesta.XML")

                            xmlNodeRdr = New XmlNodeReader(oXMLRet)
                            dsGenerarGuia = New DataSet()
                            dsGenerarGuia.ReadXml(xmlNodeRdr)

                            nMen = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(1).ToString()
                            nVal = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(2).ToString()
                            nCae = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(3).ToString()
                            nFac = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(5).ToString()
                            nSer = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(6).ToString()



                            oRecordSetUpdate = Nothing
                            oRecordSetUpdate = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                            sQuery = "Update OINV "
                            sQuery &= " set U_CAE = '" & nCae & "', U_FacNum = '" & nFac & "' , U_FacSerie = '" & nSer.Replace(nFac, "") & "', U_Mensaje = '" & nMen & "' , U_Valido = '" & nVal & "' "
                            sQuery &= " where DocNum = " & oRecordSetH.Fields.Item("DocNum").Value
                            oRecordSetUpdate.DoQuery(sQuery)


                            If Not nVal = "false" Or nVal = "False" Then


                                'Dim UrlPDF As String = "https://www.ingface.net/Ingfacereport/dtefactura.jsp?cae=" & nCae

                                UrlPDF = oRecordSetCnfgFace.Fields.Item("U_UrlPDF").Value.ToString.Trim() & nCae

                                HttpReq = DirectCast(WebRequest.Create(UrlPDF), HttpWebRequest)



                                Try
                                    Using HttpResponse As HttpWebResponse = DirectCast(HttpReq.GetResponse(), HttpWebResponse)
                                        Using Reader As New BinaryReader(HttpResponse.GetResponseStream())
                                            Dim RdByte As Byte() = Reader.ReadBytes(1 * 1024 * 1024 * 10)
                                            oRutaPdf = oRecordSetCnfgFace.Fields.Item("U_RutaPDF").Value.ToString() & "\ Factura_" & oRecordSetH.Fields.Item("DocNum").Value & ".PDF"
                                            Using FStream As New FileStream(oRutaPdf, FileMode.Create)
                                                FStream.Write(RdByte, 0, RdByte.Length)
                                                FStream.Close()

                                                'Dim MyProcess As New Process
                                                'MyProcess.StartInfo.CreateNoWindow = False
                                                'MyProcess.StartInfo.Verb = "print"

                                                ''HERE IS WHERE I WANT TO CHANGE THE PRINTER (BUT THIS COMMAND IS IGNORED)
                                                'MyProcess.StartInfo.Arguments = "ECOSYS M2035dn"

                                                'MyProcess.StartInfo.UseShellExecute = True
                                                'MyProcess.StartInfo.FileName = oRutaPdf
                                                'MyProcess.Start()

                                                '' MyProcess.WaitForExit(10000)
                                                'MyProcess.CloseMainWindow()
                                                'MyProcess.Close()

                                                'Dim MyProcess As New Process
                                                'MyProcess.StartInfo.CreateNoWindow = False
                                                'MyProcess.StartInfo.FileName = oRutaPdf
                                                'MyProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden
                                                'MyProcess.StartInfo.Verb = "print"

                                                'MyProcess.WaitForExit(10000)
                                                'MyProcess.CloseMainWindow()
                                                'MyProcess.Close()

                                                'MyProcess.StartInfo.UseShellExecute = True
                                                'MyProcess.StartInfo.FileName = oRutaPdf
                                                'MyProcess.Start()
                                                'MyProcess.WaitForExit(10000)
                                                'MyProcess.CloseMainWindow()
                                                'MyProcess.Close()

                                                'Dim ruta As String = oRutaPdf
                                                'Dim PrintTextFile As New ProcessStartInfo
                                                'PrintTextFile.UseShellExecute = True
                                                'PrintTextFile.Verb = "print"
                                                'PrintTextFile.WindowStyle = ProcessWindowStyle.Hidden
                                                'PrintTextFile.FileName = ruta
                                                'Process.Start(PrintTextFile)

                                                ''stream = New StreamReader(oRutaPdf)
                                                'Dim printer As New PrintDocument()
                                                'Dim instance As New Drawing.Printing.PrinterSettings
                                                'Dim impresosaPredt As String = instance.PrinterName
                                                'printer.PrinterSettings.PrinterName = impresosaPredt
                                                'printer.PrinterSettings.PrintFileName = oRutaPdf

                                                'printer.PrinterSettings.Copies = 1
                                                'printer.Print()

                                            End Using
                                        End Using
                                    End Using

                                Catch ex As Exception
                                    B1Connections.theAppl.SetStatusBarMessage(nMen, BoMessageTime.bmt_Medium, True)
                                End Try

                            Else

                                B1Connections.theAppl.MessageBox(nMen)


                            End If

                        End If
                    End If



                    ElseIf (form.TypeEx = "179") Then

                    oRecordSetH = Nothing
                    oRecordSetH = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                    sQuery = "Select T1.*,T0.""E_mail"",T0.""U_NIT"",T0.""Phone1"" From ORIN T1 inner join OCRD T0 On T0.""CardCode"" = T1.""CardCode"" Where T1.""DocNum"" = " & form.Items.Item("8").Specific.value
                    oRecordSetH.DoQuery(sQuery)
                    If Not String.IsNullOrEmpty(oRecordSetH.Fields.Item("CardCode").Value) Then

                        oRecordSetCnfSerie = Nothing
                        oRecordSetCnfSerie = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "Select * from [@CNFSERIE] where ""U_Serie"" = '" & oRecordSetH.Fields.Item("Series").Value & "' and ""U_Document"" = '" & oRecordSetH.Fields.Item("ObjType").Value & "' "
                        oRecordSetCnfSerie.DoQuery(sQuery)
                        oRecordSetCnfSerie.MoveFirst()

                        oRecordSetTipoCambio = Nothing
                        oRecordSetTipoCambio = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)

                        If oRecordSetCnfgFace.Fields.Item("U_Tipo").Value.ToString() = "1" Then
                            sQuery = "select ""Rate"" from ORTT where ""Currency"" = 'USD' and ""RateDate"" = CONVERT(VARCHAR(10),GETDATE(),111) "
                        ElseIf oRecordSetCnfgFace.Fields.Item("U_Tipo").Value.ToString() = "2" Then
                            sQuery = "select ""Rate"" from ORTT where ""Currency"" = 'USD' and ""RateDate"" = CURRENT_DATE"
                        End If

                        oRecordSetTipoCambio.DoQuery(sQuery)
                        oRecordSetTipoCambio.MoveFirst()


                        sXML = "<?xml version=""1.0""?>"
                        sXML &= "<S:Envelope xmlns:S=""http://schemas.xmlsoap.org/soap/envelope/"">"
                        sXML &= "   <S:Body>"
                        sXML &= "       <ns2:registrarDte xmlns:ns2=""http://listener.ingface.com/"">"
                        sXML &= "          <dte>"
                        sXML &= "               <clave>" & oRecordSetCnfgFace.Fields.Item("U_Token").Value.ToString.Trim() & "</clave>"
                        sXML &= "               <dte>"
                        sXML &= "                   <codigoEstablecimiento>" & oRecordSetCnfSerie.Fields.Item("U_Establec").Value.ToString.Trim() & "</codigoEstablecimiento>"

                        If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                            sXML &= "                   <codigoMoneda>GTQ</codigoMoneda>"
                        ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                            sXML &= "                   <codigoMoneda>USD</codigoMoneda>"
                        End If


                        If Not String.IsNullOrEmpty(oRecordSetH.Fields.Item("E_mail").Value) Then
                            sXML &= "                   <correoComprador>" & oRecordSetH.Fields.Item("E_mail").Value & "</correoComprador>"
                        Else
                            sXML &= "                   <correoComprador>N/A</correoComprador>"
                        End If



                        oRecordSetDepartamento = Nothing
                        oRecordSetDepartamento = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = " Select T3.""Name"" from OCST T3 where T3.""Code"" in (select T0.""State"" from CRD1 T0 where T0.""CardCode"" = '" & oRecordSetH.Fields.Item("CardCode").Value & "' "
                        sQuery &= " And T0.""AdresType"" = 'S' and T0.""Address"" in (select ""ShipToDef"" from OCRD T1 where T1.""CardCode"" = T0.""CardCode""))"
                        oRecordSetDepartamento.DoQuery(sQuery)
                        oRecordSetDepartamento.MoveFirst()

                        If Not String.IsNullOrEmpty(oRecordSetDepartamento.Fields.Item(0).Value) Then
                            sXML &= "                   <departamentoComprador>" & oRecordSetDepartamento.Fields.Item(0).Value & "</departamentoComprador>"
                        Else
                            sXML &= "                   <departamentoComprador>N/A</departamentoComprador>"
                        End If

                        oRecordSetDepartamentoV = Nothing
                        oRecordSetDepartamentoV = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "select T3.""Name"" from OCST T3 where T3.""Code"" in(select ""State"" from OADM)"
                        oRecordSetDepartamentoV.DoQuery(sQuery)
                        oRecordSetDepartamentoV.MoveFirst()

                        If Not String.IsNullOrEmpty(oRecordSetDepartamentoV.Fields.Item(0).Value) Then
                            sXML &= "                   <departamentoVendedor>" & oRecordSetDepartamentoV.Fields.Item(0).Value & "</departamentoVendedor>"
                        End If

                        sXML &= "                   <descripcionOtroImpuesto>N/A</descripcionOtroImpuesto>"


                        oRecordSetD = Nothing
                        oRecordSetD = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "Select * From RIN1 T0 Where T0.""DocEntry"" = " & oRecordSetH.Fields.Item("DocEntry").Value
                        oRecordSetD.DoQuery(sQuery)
                        For iCont As Integer = 0 To oRecordSetD.RecordCount - 1


                            If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                                sXML &= "                   <detalleDte>"

                                If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                    sXML &= "                      <cantidad>" & oRecordSetD.Fields.Item("Quantity").Value & "</cantidad>"
                                ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                    sXML &= "                      <cantidad>1</cantidad>"
                                End If

                                If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                    sXML &= "                       <codigoProducto>" & oRecordSetD.Fields.Item("ItemCode").Value & "</codigoProducto>"
                                ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                    sXML &= "                      <cantidad>N/A</cantidad>"
                                End If


                                sXML &= "                       <descripcionProducto>" & oRecordSetD.Fields.Item("Dscription").Value & "</descripcionProducto>"

                                If oRecordSetD.Fields.Item("TaxCode").Value = "IVA" Then
                                    sXML &= "                       <detalleImpuestosIva>" & oRecordSetD.Fields.Item("VatSum").Value & "</detalleImpuestosIva>"
                                ElseIf oRecordSetD.Fields.Item("TaxCode").Value = "EXE" Then
                                    sXML &= "                       <detalleImpuestosIva>0.000</detalleImpuestosIva>"
                                End If

                                If oRecordSetD.Fields.Item("TaxCode").Value = "IVA" Then
                                    sXML &= "                       <importeExento>0.000</importeExento>"
                                ElseIf oRecordSetD.Fields.Item("TaxCode").Value = "EXE" Then
                                    sXML &= "                       <importeExento>" & oRecordSetH.Fields.Item("DocTotal").Value & "</importeExento>"
                                End If



                                sXML &= "                       <importeNetoGravado>" & oRecordSetD.Fields.Item("PriceAfVAT").Value & "</importeNetoGravado>"
                                sXML &= "                       <importeOtrosImpuestos>0.000</importeOtrosImpuestos>"
                                sXML &= "                       <importeTotalOperacion>" & oRecordSetD.Fields.Item("GTotal").Value & "</importeTotalOperacion>"
                                sXML &= "                       <montoBruto>" & oRecordSetD.Fields.Item("LineTotal").Value & "</montoBruto>"
                                sXML &= "                       <montoDescuento>" & ((oRecordSetD.Fields.Item("PriceBefDi").Value * oRecordSetD.Fields.Item("Quantity").Value) - oRecordSetD.Fields.Item("LineTotal").Value) & "</montoDescuento>"

                                sXML &= "                       <personalizado_01>N/A</personalizado_01>"
                                sXML &= "                       <personalizado_02>N/A</personalizado_02>"
                                sXML &= "                       <personalizado_03>N/A</personalizado_03>"
                                sXML &= "                       <personalizado_04>N/A</personalizado_04>"
                                sXML &= "                       <personalizado_05>N/A</personalizado_05>"
                                sXML &= "                       <personalizado_06>N/A</personalizado_06>"
                                'Pendiente
                                sXML &= "                       <precioUnitario>" & oRecordSetD.Fields.Item("PriceBefDi").Value & "</precioUnitario>"



                            ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then

                                '''''''''''''''''''''''''''''
                                sXML &= "                   <detalleDte>"

                                If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                    sXML &= "                      <cantidad>" & oRecordSetD.Fields.Item("Quantity").Value & "</cantidad>"
                                ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                    sXML &= "                      <cantidad>1</cantidad>"
                                End If

                                If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                    sXML &= "                       <codigoProducto>" & oRecordSetD.Fields.Item("ItemCode").Value & "</codigoProducto>"
                                ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                    sXML &= "                      <cantidad>N/A</cantidad>"
                                End If

                                sXML &= "                       <descripcionProducto>" & oRecordSetD.Fields.Item("Dscription").Value & "</descripcionProducto>"

                                If oRecordSetD.Fields.Item("TaxCode").Value = "IVA" Then
                                    sXML &= "                       <detalleImpuestosIva>" & (oRecordSetD.Fields.Item("VatSum").Value * oRecordSetTipoCambio.Fields.Item(0).Value) & "</detalleImpuestosIva>"
                                ElseIf oRecordSetD.Fields.Item("TaxCode").Value = "EXE" Then
                                    sXML &= "                       <detalleImpuestosIva>0.000</detalleImpuestosIva>"
                                End If

                                If oRecordSetD.Fields.Item("TaxCode").Value = "IVA" Then
                                    sXML &= "                       <importeExento>0.000</importeExento>"
                                ElseIf oRecordSetD.Fields.Item("TaxCode").Value = "EXE" Then
                                    sXML &= "                       <importeExento>" & (oRecordSetH.Fields.Item("DocTotal").Value) & "</importeExento>"
                                End If


                                sXML &= "                       <importeNetoGravado>" & (oRecordSetD.Fields.Item("PriceAfVAT").Value * oRecordSetTipoCambio.Fields.Item(0).Value) & "</importeNetoGravado>"
                                sXML &= "                       <importeOtrosImpuestos>0.000</importeOtrosImpuestos>"
                                sXML &= "                       <importeTotalOperacion>" & (oRecordSetD.Fields.Item("GTotal").Value) & "</importeTotalOperacion>"
                                sXML &= "                       <montoBruto>" & oRecordSetD.Fields.Item("LineTotal").Value & "</montoBruto>"
                                sXML &= "                       <montoDescuento>" & (((oRecordSetD.Fields.Item("PriceBefDi").Value * oRecordSetTipoCambio.Fields.Item(0).Value) * oRecordSetD.Fields.Item("Quantity").Value) - oRecordSetD.Fields.Item("LineTotal").Value) & "</montoDescuento>"

                                sXML &= "                       <personalizado_01>N/A</personalizado_01>"
                                sXML &= "                       <personalizado_02>N/A</personalizado_02>"
                                sXML &= "                       <personalizado_03>N/A</personalizado_03>"
                                sXML &= "                       <personalizado_04>N/A</personalizado_04>"
                                sXML &= "                       <personalizado_05>N/A</personalizado_05>"
                                sXML &= "                       <personalizado_06>N/A</personalizado_06>"
                                'Pendiente
                                sXML &= "                       <precioUnitario>" & (oRecordSetD.Fields.Item("PriceBefDi").Value * oRecordSetTipoCambio.Fields.Item(0).Value) & "</precioUnitario>"



                            End If

                            If oRecordSetH.Fields.Item("DocType").Value = "I" Then
                                sXML &= "                       <tipoProducto>B</tipoProducto>"
                            ElseIf oRecordSetH.Fields.Item("DocType").Value = "S" Then
                                sXML &= "                       <tipoProducto>S</tipoProducto>"
                            End If
                            'Pendiente
                            If String.IsNullOrEmpty(oRecordSetD.Fields.Item("unitMsr").Value.ToString()) Then
                                sXML &= "                       <unidadMedida>N/A</unidadMedida>"
                            Else
                                sXML &= "                       <unidadMedida>" & oRecordSetD.Fields.Item("UomCode").Value.ToString().Trim().Substring(0, 3) & "</unidadMedida>"
                            End If

                            sXML &= "                   </detalleDte>"

                            oRecordSetD.MoveNext()



                        Next



                        If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                            sXML &= "                   <detalleImpuestosIva>" & oRecordSetH.Fields.Item("VatSum").Value & "</detalleImpuestosIva>"
                        ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                            sXML &= "                   <detalleImpuestosIva>" & (oRecordSetH.Fields.Item("VatSum").Value * oRecordSetTipoCambio.Fields.Item(0).Value) & "</detalleImpuestosIva>"
                        End If

                        If String.IsNullOrEmpty(oRecordSetH.Fields.Item("Address").Value) Then
                            sXML &= "                   <direccionComercialComprador>N/A</direccionComercialComprador>"
                        Else
                            sXML &= "                   <direccionComercialComprador>" & quitarSaltosLinea(oRecordSetH.Fields.Item("Address").Value, " ") & "</direccionComercialComprador>"
                        End If



                        oRecordSetDireccion = Nothing
                        oRecordSetDireccion = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "Select T0.""Street"" from ADM1 T0"
                        oRecordSetDireccion.DoQuery(sQuery)
                        oRecordSetDireccion.MoveFirst()

                        sXML &= "                   <direccionComercialVendedor>" & oRecordSetDireccion.Fields.Item(0).Value & "</direccionComercialVendedor>"
                        sXML &= "                   <estadoDocumento>ACTIVO</estadoDocumento>"

                        sXML &= "                   <fechaAnulacion>" & CDate(oRecordSetH.Fields.Item("TaxDate").Value).ToString("yyyy-MM-dd") & "</fechaAnulacion>"
                        sXML &= "                   <fechaDocumento>" & CDate(oRecordSetH.Fields.Item("TaxDate").Value).ToString("yyyy-MM-dd") & "</fechaDocumento>"
                        sXML &= "                   <fechaResolucion>" & CDate(oRecordSetCnfSerie.Fields.Item("U_Fecha").Value).ToString("yyyy-MM-dd") & "</fechaResolucion>"

                        sXML &= "                   <idDispositivo>" & oRecordSetCnfSerie.Fields.Item("U_Disposi").Value & "</idDispositivo>"

                        If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                            sXML &= "                   <importeBruto>" & (oRecordSetH.Fields.Item("DocTotal").Value - oRecordSetH.Fields.Item("VatSum").Value) & "</importeBruto>"
                        ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                            sXML &= "                   <importeBruto>" & (oRecordSetH.Fields.Item("DocTotal").Value - oRecordSetH.Fields.Item("VatSum").Value) & "</importeBruto>"
                        End If



                        oRecordSetImporteDesc = Nothing
                        oRecordSetImporteDesc = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)

                        If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                            sQuery = "select sum((""PriceBefDi"" * ""Quantity"") - ""LineTotal"") from RIN1 where ""DocEntry"" = " & oRecordSetH.Fields.Item("DocEntry").Value
                        ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                            sQuery = "select sum((""PriceBefDi"" * 7.5) * ""Quantity"") - (""LineTotal"") from RIN1 where ""DocEntry"" = " & oRecordSetH.Fields.Item("DocEntry").Value & " group by ""LineTotal"" "
                        End If

                        oRecordSetImporteDesc.DoQuery(sQuery)
                        oRecordSetImporteDesc.MoveFirst()

                        sXML &= "                   <importeDescuento>" & oRecordSetImporteDesc.Fields.Item(0).Value & "</importeDescuento>"


                        If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                            sXML &= "                   <importeNetoGravado>" & oRecordSetH.Fields.Item("DocTotal").Value & "</importeNetoGravado>"
                        ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                            sXML &= "                   <importeNetoGravado>" & oRecordSetH.Fields.Item("DocTotal").Value & "</importeNetoGravado>"
                        End If

                        sXML &= "                   <importeOtrosImpuestos>0.0</importeOtrosImpuestos>"
                        sXML &= "                   <importeTotalExento>0.0</importeTotalExento>"

                        If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                            sXML &= "                   <montoTotalOperacion>" & oRecordSetH.Fields.Item("DocTotal").Value & "</montoTotalOperacion>"
                        ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                            sXML &= "                   <montoTotalOperacion>" & oRecordSetH.Fields.Item("DocTotal").Value & "</montoTotalOperacion>"
                        End If


                        oRecordSetMunicipio = Nothing
                        oRecordSetMunicipio = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "select T0.""County"" from CRD1 T0 where T0.""CardCode"" = '" & oRecordSetH.Fields.Item("CardCode").Value & "' "
                        sQuery &= " And T0.""AdresType"" = 'S' and T0.""Address"" in (select ""ShipToDef"" from OCRD T1 where T1.""CardCode"" = T0.""CardCode"" ) "
                        oRecordSetMunicipio.DoQuery(sQuery)
                        oRecordSetMunicipio.MoveFirst()

                        If Not String.IsNullOrEmpty(oRecordSetMunicipio.Fields.Item(0).Value) Then
                            sXML &= "                   <municipioComprador>" & oRecordSetMunicipio.Fields.Item(0).Value & "</municipioComprador>"
                        Else
                            sXML &= "                   <municipioComprador>N/A</municipioComprador>"
                        End If

                        oRecordSetMunicipioV = Nothing
                        oRecordSetMunicipioV = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "Select ""County"" from ADM1"
                        oRecordSetMunicipioV.DoQuery(sQuery)
                        oRecordSetMunicipioV.MoveFirst()

                        sXML &= "                   <municipioVendedor>" & oRecordSetMunicipioV.Fields.Item(0).Value.ToString.Trim() & "</municipioVendedor>"
                        sXML &= "                   <nitComprador>" & oRecordSetH.Fields.Item("U_NIT").Value.ToString().Replace("-", "").Trim().TrimEnd().TrimStart() & "</nitComprador>"
                        sXML &= "                   <nitGFACE>" & oRecordSetCnfgFace.Fields.Item("U_NitFace").Value.ToString().Replace("-", "").Trim().TrimEnd().TrimStart() & "</nitGFACE>"


                        oRecordSetNitV = Nothing
                        oRecordSetNitV = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "Select T0.""TaxIdNum"" from OADM T0"
                        oRecordSetNitV.DoQuery(sQuery)
                        oRecordSetNitV.MoveFirst()
                        sXML &= "                   <nitVendedor>" & oRecordSetNitV.Fields.Item(0).Value.ToString().Replace("-", "").Trim().TrimEnd().TrimStart() & "</nitVendedor>"


                        sXML &= "                   <nombreComercialComprador>" & oRecordSetH.Fields.Item("CardName").Value & "</nombreComercialComprador>"

                        oRecordSetRazonS = Nothing
                        oRecordSetRazonS = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "Select T0.""PrintHeadr"" from OADM T0"
                        oRecordSetRazonS.DoQuery(sQuery)
                        oRecordSetRazonS.MoveFirst()



                        sXML &= "                   <nombreComercialRazonSocialVendedor>" & oRecordSetRazonS.Fields.Item(0).Value & "</nombreComercialRazonSocialVendedor>"

                        'sXML &= "                   <nombreCompletoVendedor>" & oRecordSetCnfgFace.Fields.Item("U_Nombre").Value & "</nombreCompletoVendedor>"
                        sXML &= "                   <nombreCompletoVendedor>" & oRecordSetRazonS.Fields.Item(0).Value & "</nombreCompletoVendedor>"
                        sXML &= "                   <numeroDocumento>" & oRecordSetH.Fields.Item("DocNum").Value & "</numeroDocumento>"
                        sXML &= "                   <numeroResolucion>" & oRecordSetCnfSerie.Fields.Item("U_Resolu").Value & "</numeroResolucion>"
                        sXML &= "                   <observaciones>" & oRecordSetH.Fields.Item("Comments").Value & "</observaciones>"
                        sXML &= "                   <personalizado_01>N/A</personalizado_01>"
                        sXML &= "                   <personalizado_02>N/A</personalizado_02>"
                        sXML &= "                   <personalizado_03>N/A</personalizado_03>"
                        sXML &= "                   <personalizado_04>N/A</personalizado_04>"
                        sXML &= "                   <personalizado_05>N/A</personalizado_05>"
                        sXML &= "                   <personalizado_06>N/A</personalizado_06>"
                        sXML &= "                   <personalizado_07>N/A</personalizado_07>"
                        sXML &= "                   <personalizado_08>N/A</personalizado_08>"
                        sXML &= "                   <personalizado_09>N/A</personalizado_09>"
                        sXML &= "                   <personalizado_10>N/A</personalizado_10>"
                        sXML &= "                   <personalizado_11>N/A</personalizado_11>"
                        sXML &= "                   <personalizado_12>N/A</personalizado_12>"
                        sXML &= "                   <personalizado_13>N/A</personalizado_13>"
                        sXML &= "                   <personalizado_14>N/A</personalizado_14>"
                        sXML &= "                   <personalizado_15>N/A</personalizado_15>"
                        sXML &= "                   <personalizado_16>N/A</personalizado_16>"
                        sXML &= "                   <personalizado_17>N/A</personalizado_17>"
                        sXML &= "                   <personalizado_18>N/A</personalizado_18>"
                        sXML &= "                   <personalizado_19>N/A</personalizado_19>"
                        sXML &= "                   <personalizado_20>N/A</personalizado_20>"
                        'Pendiente
                        sXML &= "                   <regimen2989>1</regimen2989>"

                        If oRecordSetCnfgFace.Fields.Item("U_Regimen").Value = "1" Then
                            sXML &= "                   <regimenISR>RET_DEFINITIVA</regimenISR>"
                        Else
                            sXML &= "                   <regimenISR>NOT_RET_DEFINITIVA</regimenISR>"
                        End If


                        sXML &= "                   <serieAutorizada>" & oRecordSetCnfSerie.Fields.Item("U_SerieDoc").Value.ToString.Trim() & "</serieAutorizada>"
                        sXML &= "                   <serieDocumento>" & oRecordSetCnfSerie.Fields.Item("U_CodeSAT").Value.ToString.Trim() & "</serieDocumento>"

                        If String.IsNullOrEmpty(oRecordSetH.Fields.Item("Phone1").Value) Then
                            sXML &= "                   <telefonoComprador>N/A</telefonoComprador>"
                        Else
                            sXML &= "                   <telefonoComprador>" & oRecordSetH.Fields.Item("Phone1").Value.ToString().Trim().Replace("-", "") & "</telefonoComprador>"
                        End If



                        If oRecordSetH.Fields.Item("DocCur").Value = "QTZ" Then
                            sXML &= "                   <tipoCambio>1.0</tipoCambio>"
                        ElseIf oRecordSetH.Fields.Item("DocCur").Value = "USD" Then
                            sXML &= "                   <tipoCambio>" & oRecordSetTipoCambio.Fields.Item(0).Value & "</tipoCambio>"
                        End If


                        sXML &= "                   <tipoDocumento>FACE</tipoDocumento>"
                        sXML &= "               </dte>"
                        sXML &= "               <usuario>" & oRecordSetCnfgFace.Fields.Item("U_Usuario").Value.ToString.Trim() & "</usuario>"
                        sXML &= "               <validador>False</validador>"
                        sXML &= "          </dte>"
                        sXML &= "       </ns2:registrarDte>"
                        sXML &= "   </S:Body>"
                        sXML &= "</S:Envelope>"

                        oXML.LoadXml(sXML)
                        oXML.Save(oRecordSetCnfgFace.Fields.Item("U_RutaXML").Value.ToString() & "\ NotaCredito # " & oRecordSetH.Fields.Item("DocNum").Value & ".XML")
                        '                        sUrl = "https://www.ingface.net/listener/ingface?wsdl"
                        sUrl = oRecordSetCnfgFace.Fields.Item("U_UrlWeb").Value.ToString.Trim()
                        oXMLRet = PostXMLTransaction(sUrl, oXML, "")
                        oXMLRet.Save(oRecordSetCnfgFace.Fields.Item("U_RutaXML").Value.ToString() & "\ NotaCredito # " & oRecordSetH.Fields.Item("DocNum").Value & "_Respuesta.XML")

                        xmlNodeRdr = New XmlNodeReader(oXMLRet)
                        dsGenerarGuia = New DataSet()
                        dsGenerarGuia.ReadXml(xmlNodeRdr)

                        nMen = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(1).ToString()
                        nVal = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(2).ToString()
                        nCae = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(3).ToString()
                        nFac = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(5).ToString()
                        nSer = dsGenerarGuia.Tables.Item("return").Rows.Item(0).Item(6).ToString()



                        oRecordSetUpdate = Nothing
                        oRecordSetUpdate = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                        sQuery = "Update ORIN "
                        sQuery &= " set U_CAE = '" & nCae & "', U_FacNum = '" & nFac & "' , U_FacSerie = '" & nSer.Replace(nFac, "") & "', U_Mensaje = '" & nMen & "' , U_Valido = '" & nVal & "' "
                        sQuery &= " where DocNum = " & oRecordSetH.Fields.Item("DocNum").Value
                        oRecordSetUpdate.DoQuery(sQuery)


                        If Not nVal = "false" Or nVal = "False" Then


                            'Dim UrlPDF As String = "https://www.ingface.net/Ingfacereport/dteNotaCredito.jsp?cae=" & nCae

                            UrlPDF = oRecordSetCnfgFace.Fields.Item("U_UrlPDF").Value.ToString.Trim() & nCae

                            HttpReq = DirectCast(WebRequest.Create(UrlPDF), HttpWebRequest)



                            Try
                                Using HttpResponse As HttpWebResponse = DirectCast(HttpReq.GetResponse(), HttpWebResponse)
                                    Using Reader As New BinaryReader(HttpResponse.GetResponseStream())
                                        Dim RdByte As Byte() = Reader.ReadBytes(1 * 1024 * 1024 * 10)
                                        oRutaPdf = oRecordSetCnfgFace.Fields.Item("U_RutaPDF").Value.ToString() & "\ NotaCredito_" & oRecordSetH.Fields.Item("DocNum").Value & ".PDF"
                                        Using FStream As New FileStream(oRutaPdf, FileMode.Create)
                                            FStream.Write(RdByte, 0, RdByte.Length)
                                            FStream.Close()

                                            'Dim MyProcess As New Process
                                            'MyProcess.StartInfo.CreateNoWindow = False
                                            'MyProcess.StartInfo.Verb = "print"

                                            ''HERE IS WHERE I WANT TO CHANGE THE PRINTER (BUT THIS COMMAND IS IGNORED)
                                            'MyProcess.StartInfo.Arguments = "ECOSYS M2035dn"

                                            'MyProcess.StartInfo.UseShellExecute = True
                                            'MyProcess.StartInfo.FileName = oRutaPdf
                                            'MyProcess.Start()

                                            '' MyProcess.WaitForExit(10000)
                                            'MyProcess.CloseMainWindow()
                                            'MyProcess.Close()

                                            'Dim MyProcess As New Process
                                            'MyProcess.StartInfo.CreateNoWindow = False
                                            'MyProcess.StartInfo.FileName = oRutaPdf
                                            'MyProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden
                                            'MyProcess.StartInfo.Verb = "print"

                                            'MyProcess.WaitForExit(10000)
                                            'MyProcess.CloseMainWindow()
                                            'MyProcess.Close()

                                            'MyProcess.StartInfo.UseShellExecute = True
                                            'MyProcess.StartInfo.FileName = oRutaPdf
                                            'MyProcess.Start()
                                            'MyProcess.WaitForExit(10000)
                                            'MyProcess.CloseMainWindow()
                                            'MyProcess.Close()

                                            'Dim ruta As String = oRutaPdf
                                            'Dim PrintTextFile As New ProcessStartInfo
                                            'PrintTextFile.UseShellExecute = True
                                            'PrintTextFile.Verb = "print"
                                            'PrintTextFile.WindowStyle = ProcessWindowStyle.Hidden
                                            'PrintTextFile.FileName = ruta
                                            'Process.Start(PrintTextFile)

                                            ''stream = New StreamReader(oRutaPdf)
                                            'Dim printer As New PrintDocument()
                                            'Dim instance As New Drawing.Printing.PrinterSettings
                                            'Dim impresosaPredt As String = instance.PrinterName
                                            'printer.PrinterSettings.PrinterName = impresosaPredt
                                            'printer.PrinterSettings.PrintFileName = oRutaPdf

                                            'printer.PrinterSettings.Copies = 1
                                            'printer.Print()

                                        End Using
                                    End Using
                                End Using

                            Catch ex As Exception
                                B1Connections.theAppl.SetStatusBarMessage(nMen, BoMessageTime.bmt_Medium, True)
                            End Try

                        Else

                            B1Connections.theAppl.MessageBox(nMen)


                        End If


                    End If




                End If


            Catch ex As Exception
                B1Connections.theAppl.SetStatusBarMessage(ex.Message, BoMessageTime.bmt_Medium, True)
            End Try


        End Sub
        Private Function GetValor(nodoPadre As Xml.XmlNode, clave As String) As Object
            Dim valor As Xml.XmlNode = nodoPadre.SelectSingleNode(clave)
            Return valor.LastChild.Value
        End Function


        Public Function PostXMLTransaction(v_strURL As String, v_objXMLDoc As XmlDocument, sToken As String) As XmlDocument
            'Declare XMLResponse document
            Dim XMLResponse As XmlDocument = Nothing

            'Declare an HTTP-specific implementation of the WebRequest class.
            Dim objHttpWebRequest As HttpWebRequest

            'Declare an HTTP-specific implementation of the WebResponse class
            Dim objHttpWebResponse As HttpWebResponse = Nothing

            'Declare a generic view of a sequence of bytes
            Dim objRequestStream As Stream = Nothing
            Dim objResponseStream As Stream = Nothing

            'Declare XMLReader
            Dim objXMLReader As XmlTextReader

            'Creates an HttpWebRequest for the specified URL.
            objHttpWebRequest = DirectCast(WebRequest.Create(v_strURL), HttpWebRequest)

            Dim sMensaje As String = ""
            Dim sLinea_Log As String = ""

            Try
                '---------- Start HttpRequest 

                If sToken <> "" Then
                    'Http Headers
                    objHttpWebRequest.Headers.Add("token", sToken)
                    'objHttpWebRequest.Headers.Add("instance", Obtiene_Valor_Parametro("312"))
                End If

                'Set HttpWebRequest properties
                Dim bytes As Byte()
                bytes = System.Text.Encoding.ASCII.GetBytes(v_objXMLDoc.InnerXml)
                objHttpWebRequest.Method = "POST"
                objHttpWebRequest.ContentLength = bytes.Length
                objHttpWebRequest.ContentType = "text/xml; encoding='utf-8'"

                ''Get Stream object 
                objRequestStream = objHttpWebRequest.GetRequestStream()

                ''Writes a sequence of bytes to the current stream 
                objRequestStream.Write(bytes, 0, bytes.Length)

                ''Close stream
                objRequestStream.Close()

                '---------- End HttpRequest

                'Sends the HttpWebRequest, and waits for a response.
                objHttpWebResponse = DirectCast(objHttpWebRequest.GetResponse(), HttpWebResponse)

                '---------- Start HttpResponse
                If objHttpWebResponse.StatusCode = HttpStatusCode.OK Then
                    'Get response stream 
                    objResponseStream = objHttpWebResponse.GetResponseStream()

                    'Load response stream into XMLReader
                    objXMLReader = New XmlTextReader(objResponseStream)

                    'Declare XMLDocument
                    Dim xmldoc As New XmlDocument()
                    xmldoc.Load(objXMLReader)

                    'Set XMLResponse object returned from XMLReader
                    XMLResponse = xmldoc

                    'Close XMLReader
                    objXMLReader.Close()
                End If

                'Close HttpWebResponse
                objHttpWebResponse.Close()
            Catch we As WebException
                'TODO: Add custom exception handling
                'Throw New Exception(we.Message)

                'If oEjecucion.IniciaMinimizado = "N" Then MsgBox(sMensaje) ' Display error message

                sLinea_Log = "Error en llamada a webservices: [" & we.Message & "]"

                B1Connections.theAppl.SetStatusBarMessage(sLinea_Log, BoMessageTime.bmt_Short, True)
            Catch ex As Exception
                'Throw New Exception(ex.Message)

                'If oEjecucion.IniciaMinimizado = "N" Then MsgBox(sMensaje) ' Display error message

                sLinea_Log = "Error en llamada a webservices: [" & ex.Message & "]"
                B1Connections.theAppl.SetStatusBarMessage(sLinea_Log, BoMessageTime.bmt_Short, True)

            Finally
                'Close connections
                objRequestStream.Close()
                objResponseStream.Close()
                objHttpWebResponse.Close()

                'Release objects
                objXMLReader = Nothing
                objRequestStream = Nothing
                objResponseStream = Nothing
                objHttpWebResponse = Nothing
                objHttpWebRequest = Nothing
            End Try

            'Return
            Return XMLResponse
        End Function
        Public Function Valida_PostXMLTransaction(v_strURL As String, v_objXMLDoc As XmlDocument, sToken As String) As Boolean
            'Declare XMLResponse document
            Dim XMLResponse As XmlDocument = Nothing

            'Declare an HTTP-specific implementation of the WebRequest class.
            Dim objHttpWebRequest As HttpWebRequest

            'Declare an HTTP-specific implementation of the WebResponse class
            Dim objHttpWebResponse As HttpWebResponse = Nothing

            'Declare a generic view of a sequence of bytes
            Dim objRequestStream As Stream = Nothing
            Dim objResponseStream As Stream = Nothing

            'Declare XMLReader
            Dim objXMLReader As XmlTextReader

            Try
                Dim myRequest As HttpWebRequest
                Dim response As HttpWebResponse = Nothing


                myRequest = CType(WebRequest.Create(v_strURL), HttpWebRequest)

                response = CType(myRequest.GetResponse(), HttpWebResponse)

                If response.StatusCode = HttpStatusCode.OK Then
                    response.Close()
                Else
                    Return False
                End If




            Catch ex As Exception
                Return False
            End Try


            'Creates an HttpWebRequest for the specified URL.
            objHttpWebRequest = DirectCast(WebRequest.Create(v_strURL), HttpWebRequest)

            Dim sMensaje As String = ""
            Dim sLinea_Log As String = ""

            Try
                '---------- Start HttpRequest 

                If sToken <> "" Then
                    'Http Headers
                    objHttpWebRequest.Headers.Add("token", sToken)
                    'objHttpWebRequest.Headers.Add("instance", Obtiene_Valor_Parametro("312"))
                End If

                'Set HttpWebRequest properties
                Dim bytes As Byte()
                bytes = System.Text.Encoding.ASCII.GetBytes(v_objXMLDoc.InnerXml)
                objHttpWebRequest.Method = "POST"
                objHttpWebRequest.ContentLength = bytes.Length
                objHttpWebRequest.ContentType = "text/xml; encoding='utf-8'"

                ''Get Stream object 
                objRequestStream = objHttpWebRequest.GetRequestStream()

                objRequestStream.Write(bytes, 0, bytes.Length)

                ''Close stream
                objRequestStream.Close()

                'objHttpWebResponse = DirectCast(objHttpWebRequest.GetResponse(), HttpWebResponse)


                Return True



            Catch we As WebException
                'TODO: Add custom exception handling
                'Throw New Exception(we.Message)

                'If oEjecucion.IniciaMinimizado = "N" Then MsgBox(sMensaje) ' Display error message

                sLinea_Log = "Error en llamada a webservices: [" & we.Message & "]"

                B1Connections.theAppl.SetStatusBarMessage(sLinea_Log, BoMessageTime.bmt_Short, True)
                'B1Connections.theAppl.SetStatusBarMessage("No Se Pudo Conectar Al Web Service, Revise Parametros De Conexión........", BoMessageTime.bmt_Long, True)
            Catch ex As Exception
                'Throw New Exception(ex.Message)

                'If oEjecucion.IniciaMinimizado = "N" Then MsgBox(sMensaje) ' Display error message

                sLinea_Log = "Error en llamada a webservices: [" & ex.Message & "]"
                B1Connections.theAppl.SetStatusBarMessage(sLinea_Log, BoMessageTime.bmt_Short, True)
                ' B1Connections.theAppl.SetStatusBarMessage("No Se Pudo Conectar Al Web Service, Revise Parametros De Conexión........", BoMessageTime.bmt_Long, True)
            Finally
                'Close connections
                'objRequestStream.Close()
                'objResponseStream.Close()
                'objHttpWebResponse.Close()

                'Release objects
                objXMLReader = Nothing
                objRequestStream = Nothing
                objResponseStream = Nothing
                objHttpWebResponse = Nothing
                objHttpWebRequest = Nothing

            End Try
            Return False
            'Return
            ' Return XMLResponse
        End Function

        <B1Listener(BoEventTypes.et_FORM_DATA_ADD, True)>
        Public Overridable Function OnBeforeFormDataAdd(ByVal pVal As BusinessObjectInfo) As Boolean
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim oBandera As Boolean
            Dim oXML As New XmlDocument
            Dim sUrl As String = ""
            Dim sXML As String = ""
            'ADD YOUR ACTION CODE HERE ...

            form = B1Connections.theAppl.Forms.ActiveForm

            sXML = "<?xml version=""1.0""?>"
            sXML &= "<S:Envelope xmlns:S=""http://schemas.xmlsoap.org/soap/envelope/"">"
            sXML &= "   <S:Body>"
            sXML &= "       <ns2:registrarDte xmlns:ns2=""http://listener.ingface.com/"">"
            sXML &= "          <dte>"
            sXML &= "               <clave>1EFD3458AA09572D52ACC0C7BC61DEE8D41D8CD98F00B204E9800998ECF8427E</clave>"
            sXML &= "               <dte>"
            sXML &= "               </dte>"
            sXML &= "               <usuario>INFORUMPRU</usuario>"
            sXML &= "               <validador>False</validador>"
            sXML &= "          </dte>"
            sXML &= "       </ns2:registrarDte>"
            sXML &= "   </S:Body>"
            sXML &= "</S:Envelope>"

            oXML.LoadXml(sXML)
            'sUrl = "https://www.ingface.net:443/listener/ingface"
            sUrl = "https://www.ingface.net/listener/ingface?wsdl"
            oBandera = Valida_PostXMLTransaction(sUrl, oXML, "")

            If oBandera = False Then
                'B1Connections.theAppl.SetStatusBarMessage("No Se Pudo Conectar Al Web Service, Revise Parametros De Conexión........", BoMessageTime.bmt_Long, True)
                B1Connections.theAppl.MessageBox("No Se Puede Conectar Al Web Service, Revise Conexión A Internet o Parametros.")
                Return False
            End If

            Return True
        End Function

    End Class
End Namespace
