'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica
    
    Public Class Factura_Electronica_Db
        Inherits B1Db
        
        Public Sub New()
            MyBase.New
            '   Tables = New B1DbTable() {New B1DbTable("@FACTURAS", "Facturas Generadas", BoUTBTableType.bott_NoObject), New B1DbTable("@PRUEBA", "prueba", BoUTBTableType.bott_NoObject)}
            'Columns = New B1DbColumn() {New B1DbColumn("@FACTURAS", "CardCode", "Socio De Negocio", BoFieldTypes.db_Alpha, BoFldSubTypes.st_None, 50, false, New B1WizardBase.B1DbValidValue(-1) {}, -1), New B1DbColumn("@PRUEBA", "Prueba", "fasfa", BoFieldTypes.db_Alpha, BoFldSubTypes.st_None, 4, false, New B1WizardBase.B1DbValidValue(-1) {}, -1)}
        End Sub
    End Class
End Namespace
