Option Strict Off
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.IO
Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM
Imports System.Net.Http
Imports Newtonsoft.Json
Imports System.Net
Imports System.Threading.Tasks
Imports System.Xml
Imports System.Collections.Generic
Imports System.Globalization

Namespace Factura_Electronica

    Public Class Factura_Electronica
        Inherits B1AddOn

        Public Sub New()
            MyBase.New
            'ADD YOUR INITIALIZATION CODE HERE	...
        End Sub

        Public Overrides Sub OnShutDown()
            'ADD YOUR TERMINATION CODE HERE	...
        End Sub

        Public Overrides Sub OnCompanyChanged()
            'ADD YOUR COMPANY CHANGE CODE HERE	...
        End Sub

        Public Overrides Sub OnLanguageChanged(ByVal language As BoLanguages)
            InitializeMenus()
            'ADD YOUR LANGUAGE CHANGE CODE HERE	...
        End Sub

        Public Overrides Sub OnStatusBarErrorMessage(ByVal txt As String)
            'ADD YOUR CODE HERE	...
        End Sub

        Public Overrides Sub OnStatusBarSuccessMessage(ByVal txt As String)
            'ADD YOUR CODE HERE	...
        End Sub

        Public Overrides Sub OnStatusBarWarningMessage(ByVal txt As String)
            'ADD YOUR CODE HERE	...
        End Sub

        Public Overrides Sub OnStatusBarNoTypedMessage(ByVal txt As String)
            'ADD YOUR CODE HERE	...
        End Sub

        Public Overrides Function OnBeforeProgressBarCreated() As Boolean
            'ADD YOUR CODE HERE	...
            Return True
        End Function

        Public Overrides Function OnAfterProgressBarCreated() As Boolean
            'ADD YOUR CODE HERE	...
            Return True
        End Function

        Public Overrides Function OnBeforeProgressBarStopped(ByVal success As Boolean) As Boolean
            'ADD YOUR CODE HERE	...
            Return True
        End Function

        Public Overrides Function OnAfterProgressBarStopped(ByVal success As Boolean) As Boolean
            'ADD YOUR CODE HERE	...
            Return True
        End Function

        Public Overrides Function OnProgressBarReleased() As Boolean
            'ADD YOUR CODE HERE	...
            Return True
        End Function
        Public Shared Sub Main()

            Dim retCode As Integer = 0
            Dim connStr As String = ""
            Dim iDias As Integer = 0
            Dim xkey As String = ""
            Dim cnxType As B1WizardBase.B1Connections.ConnectionType = B1WizardBase.B1Connections.ConnectionType.MultipleAddOns
            'CHANGE ADDON IDENTIFIER BEFORE RELEASING TO CUSTOMER (Solution Identifier)
            Dim addOnIdentifierStr As String = Nothing

            If (System.Environment.GetCommandLineArgs().Length = 1) Then
                connStr = B1Connections.connStr
            Else
                connStr = System.Environment.GetCommandLineArgs().GetValue(1).ToString()
            End If
            Try
                'INIT CONNECTIONS
                retCode = B1Connections.Init(connStr, addOnIdentifierStr, cnxType)
                'CONNECTION FAILED
                If (retCode <> 0) Then
                    System.Windows.Forms.MessageBox.Show("ERROR - Connection failed: " + B1Connections.diCompany.GetLastErrorDescription())
                    Return
                End If

                B1Connections.theAppl.StatusBar.SetText("Validando licencia...", BoMessageTime.bmt_Short, BoStatusBarMessageType.smt_Success)

                'CREATE DB
                B1Connections.theAppl.StatusBar.SetText("Addon Edx FEL, creando / actualizando metadata...", BoMessageTime.bmt_Short, BoStatusBarMessageType.smt_Success)
                Crea_Metadata()
                ' Send_Email("dperez@inforumsol.com")
                ' correos_s()
                'Enviar_Correo("prueba")
                'MANAGE COCKPITS
                If ((cnxType = B1WizardBase.B1Connections.ConnectionType.SSO) _
                            OrElse (cnxType = B1WizardBase.B1Connections.ConnectionType.MultipleAddOns)) Then
                    Dim addOnDb As Factura_Electronica_Db = New Factura_Electronica_Db()
                    addOnDb.Add(B1Connections.diCompany)
                    Dim addOnCockpit As Factura_Electronica_Cockpits = New Factura_Electronica_Cockpits()
                    addOnCockpit.Manage(B1Connections.theAppl, B1Connections.diCompany)
                End If
                'CREATE ADD-ON
                B1Connections.theAppl.StatusBar.SetText("Addon Edx Fel Conectado...", BoMessageTime.bmt_Short, BoStatusBarMessageType.smt_Success)
                Dim addOn As Factura_Electronica = New Factura_Electronica()
                Dim oMenu As SAPbouiCOM.Menus
                Dim oMenuItem As SAPbouiCOM.MenuItem

                oMenu = B1Connections.theAppl.Menus
                oMenuItem = B1Connections.theAppl.Menus.Item("mnElecFact")
                oMenuItem.Image = System.Windows.Forms.Application.StartupPath & "\Images\fac.png"

                System.Windows.Forms.Application.Run()
            Catch com_err As System.Runtime.InteropServices.COMException

                'HANDLE ANY COMException HERE
                System.Windows.Forms.MessageBox.Show("ERROR - Connection failed:   " + com_err.Message)
                'Main()

            End Try
        End Sub
        Private Shared Function Crea_Metadata() As Integer

            'Dim oUFields As SAPbobsCOM.UserFieldsMD

            Dim oUserObjectMD As SAPbobsCOM.UserObjectsMD
            Dim oArrayValues As New ArrayList
            Dim oArrayDescriptions As New ArrayList
            Dim sErrMsg As String
            Dim lRetCode As Integer

            Try

                '''''''''''''''''''''''''''''''''''''''''''''''''''''
                AddSAPUserTable(B1Connections.diCompany, "CNFGLIC", "Configuracion De Licencia", SAPbobsCOM.BoUTBTableType.bott_NoObject)
                AddSAPUserFields(B1Connections.diCompany, "@CNFGLIC", "Licencia", "Licencia", SAPbobsCOM.BoFieldTypes.db_Memo, 200, "", SAPbobsCOM.BoFldSubTypes.st_None)


                AddSAPUserTable(B1Connections.diCompany, "QUERYH", "Query Manager Encabezado", SAPbobsCOM.BoUTBTableType.bott_NoObject)
                AddSAPUserFields(B1Connections.diCompany, "@QUERYH", "Etiqueta", "Etiqueta", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@QUERYH", "Query", "Query", SAPbobsCOM.BoFieldTypes.db_Memo, 30000, "", SAPbobsCOM.BoFldSubTypes.st_None)

                AddSAPUserTable(B1Connections.diCompany, "QUERYD", "Query Manager Detalle", SAPbobsCOM.BoUTBTableType.bott_NoObject)
                AddSAPUserFields(B1Connections.diCompany, "@QUERYD", "Etiqueta", "Etiqueta", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@QUERYD", "Query", "Query", SAPbobsCOM.BoFieldTypes.db_Memo, 30000, "", SAPbobsCOM.BoFldSubTypes.st_None)

                AddSAPUserTable(B1Connections.diCompany, "QUERYP", "Personalizados Detalle", SAPbobsCOM.BoUTBTableType.bott_NoObject)
                AddSAPUserFields(B1Connections.diCompany, "@QUERYP", "Etiqueta", "Etiqueta", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@QUERYP", "Query", "Query", SAPbobsCOM.BoFieldTypes.db_Memo, 30000, "", SAPbobsCOM.BoFldSubTypes.st_None)


                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("FACT")
                oArrayValues.Add("FCAM")
                oArrayValues.Add("FPEQ")
                oArrayValues.Add("FCAP")
                oArrayValues.Add("FESP")
                oArrayValues.Add("NABN")
                oArrayValues.Add("RDON")
                oArrayValues.Add("RECI")
                oArrayValues.Add("NDEB")
                oArrayValues.Add("NCRE")
                oArrayValues.Add("EXPO")
                oArrayValues.Add("CAXP")


                oArrayDescriptions.Add("Factura")
                oArrayDescriptions.Add("Factura Cambiaria")
                oArrayDescriptions.Add("Factura Pequeño Contribuyente")
                oArrayDescriptions.Add("Factura Cambiaria Pequeño Contribuyente")
                oArrayDescriptions.Add("Factura Especial")
                oArrayDescriptions.Add("Nota De Abono")
                oArrayDescriptions.Add("Recibo por Donacion")
                oArrayDescriptions.Add("Recibo")
                oArrayDescriptions.Add("Nota De Debito")
                oArrayDescriptions.Add("Nota de Crédito")
                oArrayDescriptions.Add("Factura Exportacion")
                oArrayDescriptions.Add("Factura Cambiaria de Exportacion")



                AddSAPUserFields(B1Connections.diCompany, "@QUERYH", "Document", "Transaccion", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)



                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("FACT")
                oArrayValues.Add("FCAM")
                oArrayValues.Add("FPEQ")
                oArrayValues.Add("FCAP")
                oArrayValues.Add("FESP")
                oArrayValues.Add("NABN")
                oArrayValues.Add("RDON")
                oArrayValues.Add("RECI")
                oArrayValues.Add("NDEB")
                oArrayValues.Add("NCRE")
                oArrayValues.Add("EXPO")
                oArrayValues.Add("CAXP")


                oArrayDescriptions.Add("Factura")
                oArrayDescriptions.Add("Factura Cambiaria")
                oArrayDescriptions.Add("Factura Pequeño Contribuyente")
                oArrayDescriptions.Add("Factura Cambiaria Pequeño Contribuyente")
                oArrayDescriptions.Add("Factura Especial")
                oArrayDescriptions.Add("Nota De Abono")
                oArrayDescriptions.Add("Recibo por Donacion")
                oArrayDescriptions.Add("Recibo")
                oArrayDescriptions.Add("Nota De Debito")
                oArrayDescriptions.Add("Nota de Crédito")
                oArrayDescriptions.Add("Factura Exportacion")
                oArrayDescriptions.Add("Factura Cambiaria de Exportacion")



                AddSAPUserFields(B1Connections.diCompany, "@QUERYD", "Document", "Transaccion", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)



                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("FACT")
                oArrayValues.Add("FCAM")
                oArrayValues.Add("FPEQ")
                oArrayValues.Add("FCAP")
                oArrayValues.Add("FESP")
                oArrayValues.Add("NABN")
                oArrayValues.Add("RDON")
                oArrayValues.Add("RECI")
                oArrayValues.Add("NDEB")
                oArrayValues.Add("NCRE")
                oArrayValues.Add("EXPO")
                oArrayValues.Add("CAXP")


                oArrayDescriptions.Add("Factura")
                oArrayDescriptions.Add("Factura Cambiaria")
                oArrayDescriptions.Add("Factura Pequeño Contribuyente")
                oArrayDescriptions.Add("Factura Cambiaria Pequeño Contribuyente")
                oArrayDescriptions.Add("Factura Especial")
                oArrayDescriptions.Add("Nota De Abono")
                oArrayDescriptions.Add("Recibo por Donacion")
                oArrayDescriptions.Add("Recibo")
                oArrayDescriptions.Add("Nota De Debito")
                oArrayDescriptions.Add("Nota de Crédito")
                oArrayDescriptions.Add("Factura Exportacion")
                oArrayDescriptions.Add("Factura Cambiaria de Exportacion")


                AddSAPUserFields(B1Connections.diCompany, "@QUERYP", "Document", "Transaccion", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)


                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("BB")
                oArrayValues.Add("BC")
                oArrayValues.Add("BA")
                oArrayValues.Add("S")
                oArrayValues.Add("I")
                oArrayValues.Add("E")
                oArrayValues.Add("N")

                oArrayDescriptions.Add("Bien")
                oArrayDescriptions.Add("Combustible")
                oArrayDescriptions.Add("Activos")
                oArrayDescriptions.Add("Servicio")
                oArrayDescriptions.Add("Importacion/Exportacion")
                oArrayDescriptions.Add("Exento")
                oArrayDescriptions.Add("No Aplica")

                AddSAPUserFields(B1Connections.diCompany, "OITM", "TipoArticuloBS", "Tipo Articulo", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("01")
                oArrayValues.Add("02")

                oArrayDescriptions.Add("Cobro adicional")
                oArrayDescriptions.Add("Cobro por cuenta ajena (PXC)")

                AddSAPUserFields(B1Connections.diCompany, "OITM", "tipo_articuloCA", "Articulo CA", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)

                ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' PERSONALIZADOS ENCABEZADO 0'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
                AddSAPUserTable(B1Connections.diCompany, "PERSONAH", "Campos Personalizados", SAPbobsCOM.BoUTBTableType.bott_NoObject)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("E")
                oArrayValues.Add("D")
                oArrayValues.Add("T")
                oArrayValues.Add("F")


                oArrayDescriptions.Add("Entero")
                oArrayDescriptions.Add("Decimal")
                oArrayDescriptions.Add("Texto")
                oArrayDescriptions.Add("Fecha")

                AddSAPUserFields(B1Connections.diCompany, "@PERSONAH", "Adenda", "Nombre Adenda", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@PERSONAH", "Type", "Tipo De Dato", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)
                AddSAPUserFields(B1Connections.diCompany, "@PERSONAH", "Field", "Campo SAP", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None, Nothing, Nothing, "N/A")
                AddSAPUserFields(B1Connections.diCompany, "@PERSONAH", "Format", "Formato Fecha", SAPbobsCOM.BoFieldTypes.db_Alpha, 15, "", SAPbobsCOM.BoFldSubTypes.st_None)


                ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

                ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' TABLA DE PAGO CAJAS '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
                AddSAPUserTable(B1Connections.diCompany, "INFORESOLU", "Resolucion PC", SAPbobsCOM.BoUTBTableType.bott_NoObject)

                AddSAPUserFields(B1Connections.diCompany, "@INFORESOLU", "NumeroR", "Numero R", SAPbobsCOM.BoFieldTypes.db_Alpha, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@INFORESOLU", "FechaR", "Fecha R", SAPbobsCOM.BoFieldTypes.db_Date, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)

                ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

                'Tabla Localidad
                AddSAPUserTable(B1Connections.diCompany, "CONFEL", "Configuracion Certificador", SAPbobsCOM.BoUTBTableType.bott_MasterData)
                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "NitFace", "NIT Certificador", SAPbobsCOM.BoFieldTypes.db_Alpha, 15, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "UrlFel", "Url Certificador", SAPbobsCOM.BoFieldTypes.db_Memo, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "Correo", "Correo Copia", SAPbobsCOM.BoFieldTypes.db_Memo, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "AreaName", "Nombre del Area", SAPbobsCOM.BoFieldTypes.db_Alpha, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("Y")
                oArrayValues.Add("N")

                oArrayDescriptions.Add("Yes")
                oArrayDescriptions.Add("No")

                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "Free", "Amplia Descripcion", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("Y")
                oArrayValues.Add("N")

                oArrayDescriptions.Add("Yes")
                oArrayDescriptions.Add("No")

                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "Combo", "Combo", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("Y")
                oArrayValues.Add("N")

                oArrayDescriptions.Add("Yes")
                oArrayDescriptions.Add("No")

                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "PerDetalle", "Detalle", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("Y")
                oArrayValues.Add("N")

                oArrayDescriptions.Add("Yes")
                oArrayDescriptions.Add("No")

                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "CobroAje", "Cuenta Aje", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)


                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("Y")
                oArrayValues.Add("N")

                oArrayDescriptions.Add("Yes")
                oArrayDescriptions.Add("No")

                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "Agente", "Retiene IVA", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)


                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("TRI")
                oArrayValues.Add("RET")
                oArrayValues.Add("DIR")
                oArrayValues.Add("EXE")

                oArrayDescriptions.Add("Sujeto a pagos trimestrales")
                oArrayDescriptions.Add("Sujeto a retención definitiva")
                oArrayDescriptions.Add("Sujeto a pago directo")
                oArrayDescriptions.Add("Exento del ISR")

                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "RegISR", "Regimen ISR", SAPbobsCOM.BoFieldTypes.db_Alpha, 30, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)


                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "RutaXML", "Ruta Archivos Enviados", SAPbobsCOM.BoFieldTypes.db_Memo, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "RutaRes", "Ruta Archivos Respuesta", SAPbobsCOM.BoFieldTypes.db_Memo, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)


                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("GEN")
                oArrayValues.Add("EXE")
                oArrayValues.Add("PEQ")

                oArrayDescriptions.Add("General")
                oArrayDescriptions.Add("Exento")
                oArrayDescriptions.Add("Pequeño Contribuyente")

                AddSAPUserFields(B1Connections.diCompany, "@CONFEL", "IVA", "Tipo Afiliacion", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)

                oUserObjectMD = B1Connections.diCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.oUserObjectsMD)

                If oUserObjectMD.GetByKey("CONFEL") = False Then
                    oUserObjectMD.CanCancel = SAPbobsCOM.BoYesNoEnum.tYES
                    oUserObjectMD.CanClose = SAPbobsCOM.BoYesNoEnum.tNO
                    oUserObjectMD.CanCreateDefaultForm = SAPbobsCOM.BoYesNoEnum.tNO
                    oUserObjectMD.CanDelete = SAPbobsCOM.BoYesNoEnum.tNO
                    oUserObjectMD.CanFind = SAPbobsCOM.BoYesNoEnum.tYES
                    oUserObjectMD.CanYearTransfer = SAPbobsCOM.BoYesNoEnum.tNO
                    oUserObjectMD.Code = "CONFEL"
                    oUserObjectMD.Name = "CONFEL"
                    oUserObjectMD.ObjectType = SAPbobsCOM.BoUDOObjType.boud_MasterData
                    oUserObjectMD.TableName = "CONFEL"

                    oUserObjectMD.FindColumns.ColumnAlias = "Code"
                    oUserObjectMD.FindColumns.ColumnDescription = "Código"
                    oUserObjectMD.FindColumns.Add()

                    oUserObjectMD.FindColumns.ColumnAlias = "Name"
                    oUserObjectMD.FindColumns.ColumnDescription = "Nombre"

                    lRetCode = oUserObjectMD.Add()

                    '// check for errors in the process
                    If lRetCode <> 0 Then
                        B1Connections.diCompany.GetLastError(lRetCode, sErrMsg)
                        MsgBox(sErrMsg)
                    End If
                End If

                System.Runtime.InteropServices.Marshal.ReleaseComObject(oUserObjectMD)
                oUserObjectMD = Nothing

                '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
                AddSAPUserFields(B1Connections.diCompany, "OCRD", "NIT", "NIT", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)

                ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

                '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
                AddSAPUserFields(B1Connections.diCompany, "INV1", "TextoLargo", "Complemento Descripcion", SAPbobsCOM.BoFieldTypes.db_Alpha, 250, "", SAPbobsCOM.BoFldSubTypes.st_None)

                AddSAPUserFields(B1Connections.diCompany, "RIN1", "TextoLargo", "Complemento Descripcion", SAPbobsCOM.BoFieldTypes.db_Alpha, 250, "", SAPbobsCOM.BoFldSubTypes.st_None)

                ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

                AddSAPUserFields(B1Connections.diCompany, "OINV", "NITCA", "NIT CA", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "NumeroCA", "Numero CA", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "FechaCA", "Fecha CA", SAPbobsCOM.BoFieldTypes.db_Date, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)


                AddSAPUserFields(B1Connections.diCompany, "OINV", "DocSerie", "Serie de Documento", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "DocNum", "Numero de Documento", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "FacNit", "NIT", SAPbobsCOM.BoFieldTypes.db_Alpha, 25, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "DocNom", "Nombre de Documento", SAPbobsCOM.BoFieldTypes.db_Alpha, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "Personeria", "Tipo Personeria", SAPbobsCOM.BoFieldTypes.db_Alpha, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "FacResolucion", "Res Pago Cajas", SAPbobsCOM.BoFieldTypes.db_Alpha, 70, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "ResolucionFecha", "Fecha de Resolucion", SAPbobsCOM.BoFieldTypes.db_Date, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "FacFecha", "Fecha de Documento", SAPbobsCOM.BoFieldTypes.db_Date, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "Fac_FechaC", "Fecha Certificacion", SAPbobsCOM.BoFieldTypes.db_Alpha, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "NContingencia", "Numero de Contingencia", SAPbobsCOM.BoFieldTypes.db_Alpha, 150, "", SAPbobsCOM.BoFldSubTypes.st_None)


                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("FC")
                oArrayValues.Add("NC")
                oArrayValues.Add("FCE")
                oArrayValues.Add("FPQ")

                oArrayDescriptions.Add("Factura")
                oArrayDescriptions.Add("Nota de Credito")
                oArrayDescriptions.Add("Factura Electronica")
                oArrayDescriptions.Add("Factura Pequeño Contribuyente")

                AddSAPUserFields(B1Connections.diCompany, "OINV", "TIPO_DOCUMENTO", "Tipo Documento", SAPbobsCOM.BoFieldTypes.db_Alpha, 5, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions, "FC")
                AddSAPUserFields(B1Connections.diCompany, "OINV", "Tienda", "Sucursal", SAPbobsCOM.BoFieldTypes.db_Alpha, 8, "", SAPbobsCOM.BoFldSubTypes.st_None)


                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("EXW")
                oArrayValues.Add("FCA")
                oArrayValues.Add("FAS")
                oArrayValues.Add("FOB")
                oArrayValues.Add("CFR")
                oArrayValues.Add("CIF")
                oArrayValues.Add("CPT")
                oArrayValues.Add("CIP")
                oArrayValues.Add("DDP")
                oArrayValues.Add("DAP")
                oArrayValues.Add("DAT")
                oArrayValues.Add("ZZZ")


                oArrayDescriptions.Add("En Fabrica")
                oArrayDescriptions.Add("Libre transportista")
                oArrayDescriptions.Add("Libre al costado del buque")
                oArrayDescriptions.Add("Libre a bordo")
                oArrayDescriptions.Add("Costo y Flete")
                oArrayDescriptions.Add("Costo,seguro y flete")
                oArrayDescriptions.Add("Flete pagado hasta")
                oArrayDescriptions.Add("Flete y seguro pagado hasta")
                oArrayDescriptions.Add("Entregado en destino con derecho pagados")
                oArrayDescriptions.Add("Entregada en lugar")
                oArrayDescriptions.Add("Entregada en terminal")
                oArrayDescriptions.Add("Otro")

                AddSAPUserFields(B1Connections.diCompany, "OINV", "Incoterms", "Tipos Incoterms", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)


                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("V")
                oArrayValues.Add("A")


                oArrayDescriptions.Add("Vigente")
                oArrayDescriptions.Add("Anulada")


                AddSAPUserFields(B1Connections.diCompany, "OINV", "STATUS_NC", "Estatus Docto LibroCV", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions, "V")


                AddSAPUserFields(B1Connections.diCompany, "OINV", "CAE", "CAE", SAPbobsCOM.BoFieldTypes.db_Memo, 200, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "Mensaje", "Mensaje", SAPbobsCOM.BoFieldTypes.db_Memo, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("4,1")
                oArrayValues.Add("4,2")
                oArrayValues.Add("4,3")
                oArrayValues.Add("4,4")
                oArrayValues.Add("4,5")
                oArrayValues.Add("4,6")
                oArrayValues.Add("4,7")
                oArrayValues.Add("4,8")
                oArrayValues.Add("4,9")
                oArrayValues.Add("4,10")
                oArrayValues.Add("4,11")
                oArrayValues.Add("4,12")

                oArrayDescriptions.Add("Exenta del IVA (art. 7 núm 4 Ley del IVA)")
                oArrayDescriptions.Add("Exenta del IVA (art. 7 núm 4 Ley del IVA)")
                oArrayDescriptions.Add("Exenta del IVA (art. 7 núm 5 Ley del IVA)")
                oArrayDescriptions.Add("Exenta del IVA (art. 7 núm 5 Ley del IVA)")
                oArrayDescriptions.Add("Exenta del IVA (art. 7 núm 10 Ley del IVA)")
                oArrayDescriptions.Add("Exenta del IVA (art. 7 núm 13 Ley del IVA)")
                oArrayDescriptions.Add("Exenta del IVA (art. 7 núm 14 Ley del IVA)")
                oArrayDescriptions.Add("Exenta del IVA (art. 8 núm 1 Ley del IVA)")
                oArrayDescriptions.Add("Exenta del IVA (art. 7 núm 15 Ley del IVA)")
                oArrayDescriptions.Add("Esta Factura no incluye IVA (art. 55 Ley del IVA)")
                oArrayDescriptions.Add("No afecta al IVA (Decreto 29-89 ley de Maquila)")
                oArrayDescriptions.Add("No afecta al IVA (Decreto 65-89 ley de Zonas Francas)")

                AddSAPUserFields(B1Connections.diCompany, "OINV", "Frases", "Frases SAT", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("false")
                oArrayValues.Add("true")


                oArrayDescriptions.Add("false")
                oArrayDescriptions.Add("true")

                '  MsgBox("11")
                AddSAPUserFields(B1Connections.diCompany, "OINV", "Valido", "Valido", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions, "false")

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("N")
                oArrayValues.Add("Y")


                oArrayDescriptions.Add("No")
                oArrayDescriptions.Add("Yes")

                AddSAPUserFields(B1Connections.diCompany, "OINV", "Antiguo", "Regimen Antiguo", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("N")
                oArrayValues.Add("Y")

                oArrayDescriptions.Add("No")
                oArrayDescriptions.Add("Yes")

                AddSAPUserFields(B1Connections.diCompany, "OINV", "Agrupa", "Agrupa Detalle", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "Detfact", "Detalle Fact", SAPbobsCOM.BoFieldTypes.db_Alpha, 230, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "Detfact2", "Detalle Fact", SAPbobsCOM.BoFieldTypes.db_Alpha, 230, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "SubTotal1", "Subtotal", SAPbobsCOM.BoFieldTypes.db_Alpha, 230, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "SubTotal2", "Subtotal2", SAPbobsCOM.BoFieldTypes.db_Alpha, 230, "", SAPbobsCOM.BoFldSubTypes.st_None)

                AddSAPUserFields(B1Connections.diCompany, "OINV", "RSGFACE", "Resolucion Antiguo", SAPbobsCOM.BoFieldTypes.db_Alpha, 30, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "NDGFACE", "Num Doc Antiguo", SAPbobsCOM.BoFieldTypes.db_Alpha, 12, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "SGFACE", "Serie Doc Antiguo", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "OINV", "FeGFACE", "Fecha FEL", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)

                AddSAPUserFields(B1Connections.diCompany, "ORCT", "DocSerie", "Serie Factura", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "ORCT", "DocNum", "Numero Factura", SAPbobsCOM.BoFieldTypes.db_Alpha, 20, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "ORCT", "CAE", "CAE", SAPbobsCOM.BoFieldTypes.db_Memo, 200, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "ORCT", "Mensaje", "Mensaje", SAPbobsCOM.BoFieldTypes.db_Memo, 100, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "ORCT", "Valido", "Valido", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)

                '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
                AddSAPUserTable(B1Connections.diCompany, "SERIESH", "Configuracion EstablecimientoH", SAPbobsCOM.BoUTBTableType.bott_MasterData)
                AddSAPUserTable(B1Connections.diCompany, "SERIESO", "Configuracion EstablecimientoD", SAPbobsCOM.BoUTBTableType.bott_MasterDataLines)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("13")
                oArrayValues.Add("14")
                oArrayValues.Add("DN")
                oArrayValues.Add("24")
                oArrayValues.Add("18")

                oArrayDescriptions.Add("Factura Cliente")
                oArrayDescriptions.Add("Nota De Credito")
                oArrayDescriptions.Add("Nota De Debito")
                oArrayDescriptions.Add("Recibos")
                oArrayDescriptions.Add("Factura Especial")



                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Document", "Transaccion", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Serie", "Serie", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None)

                oArrayValues.Clear()
                oArrayDescriptions.Clear()

                oArrayValues.Add("FACT")
                oArrayValues.Add("FCAM")
                oArrayValues.Add("FPEQ")
                oArrayValues.Add("FCAP")
                oArrayValues.Add("FESP")
                oArrayValues.Add("NABN")
                oArrayValues.Add("RDON")
                oArrayValues.Add("RECI")
                oArrayValues.Add("NDEB")
                oArrayValues.Add("NCRE")
                oArrayValues.Add("EXPO")
                oArrayValues.Add("CAXP")


                oArrayDescriptions.Add("Factura")
                oArrayDescriptions.Add("Factura Cambiaria")
                oArrayDescriptions.Add("Factura Pequeño Contribuyente")
                oArrayDescriptions.Add("Factura Cambiaria Pequeño Contribuyente")
                oArrayDescriptions.Add("Factura Especial")
                oArrayDescriptions.Add("Nota De Abono")
                oArrayDescriptions.Add("Recibo por Donacion")
                oArrayDescriptions.Add("Recibo")
                oArrayDescriptions.Add("Nota De Debito")
                oArrayDescriptions.Add("Nota de Crédito")
                oArrayDescriptions.Add("Factura Exportacion")
                oArrayDescriptions.Add("Factura Cambiaria de Exportacion")

                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Type", "Tipo De Dato", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None, oArrayValues, oArrayDescriptions)


                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "NomSerie", "Nombre serie", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "RutaPDF", "Ruta Archivos PDF", SAPbobsCOM.BoFieldTypes.db_Memo, 200, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Codigo", "Codigo Establecimiento", SAPbobsCOM.BoFieldTypes.db_Alpha, 5, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "NombreEs", "Nombre Establecimiento", SAPbobsCOM.BoFieldTypes.db_Memo, 200, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Direcc", "Direccion Establecimiento", SAPbobsCOM.BoFieldTypes.db_Memo, 600, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Postal", "Codigo Postal", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Depart", "Departamento", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Muni", "Municipio", SAPbobsCOM.BoFieldTypes.db_Alpha, 50, "", SAPbobsCOM.BoFldSubTypes.st_None)
                AddSAPUserFields(B1Connections.diCompany, "@SERIESO", "Telefon", "Telefono Establecimiento", SAPbobsCOM.BoFieldTypes.db_Alpha, 10, "", SAPbobsCOM.BoFldSubTypes.st_None)


                oUserObjectMD = B1Connections.diCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.oUserObjectsMD)

                If oUserObjectMD.GetByKey("SERIESH") = False Then
                    oUserObjectMD.CanCancel = SAPbobsCOM.BoYesNoEnum.tYES
                    oUserObjectMD.CanClose = SAPbobsCOM.BoYesNoEnum.tNO
                    oUserObjectMD.CanCreateDefaultForm = SAPbobsCOM.BoYesNoEnum.tNO
                    oUserObjectMD.CanDelete = SAPbobsCOM.BoYesNoEnum.tNO
                    oUserObjectMD.CanFind = SAPbobsCOM.BoYesNoEnum.tYES
                    oUserObjectMD.CanYearTransfer = SAPbobsCOM.BoYesNoEnum.tNO
                    oUserObjectMD.Code = "SERIESH"
                    oUserObjectMD.Name = "SERIESH"
                    oUserObjectMD.ObjectType = SAPbobsCOM.BoUDOObjType.boud_MasterData
                    oUserObjectMD.TableName = "SERIESH"
                    oUserObjectMD.ChildTables.TableName = "SERIESO"

                    oUserObjectMD.FindColumns.ColumnAlias = "Code"
                    oUserObjectMD.FindColumns.ColumnDescription = "Código"
                    oUserObjectMD.FindColumns.Add()

                    oUserObjectMD.FindColumns.ColumnAlias = "Name"
                    oUserObjectMD.FindColumns.ColumnDescription = "Nombre"

                    lRetCode = oUserObjectMD.Add()

                    '// check for errors in the process
                    If lRetCode <> 0 Then
                        B1Connections.diCompany.GetLastError(lRetCode, sErrMsg)
                        MsgBox(sErrMsg)
                    End If

                End If


                System.Runtime.InteropServices.Marshal.ReleaseComObject(oUserObjectMD)
                oUserObjectMD = Nothing


                Return 1

            Catch ex As Exception
                Throw ex
            End Try


        End Function


        Public Shared Function AddSAPUserTable(ByRef oCompany As SAPbobsCOM.Company, ByVal tableName As String, ByVal tableDescription As String, ByVal tableType As SAPbobsCOM.BoUTBTableType) As Boolean
            ' Tabla en Base de Sap donde se guardan las UserTableMD: OUTB
            Dim userTableMD As SAPbobsCOM.UserTablesMD
            Dim result As Integer
            Dim lErrCode As Integer
            Dim sErrMsg As String = ""

            userTableMD = Nothing
            userTableMD = CType(oCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.oUserTables), SAPbobsCOM.UserTablesMD)

            Try

                If Not userTableMD.GetByKey(tableName) Then

                    userTableMD.TableName = tableName
                    userTableMD.TableDescription = tableDescription
                    userTableMD.TableType = CType(tableType, SAPbobsCOM.BoUTBTableType)

                    result = userTableMD.Add()

                    If result > 0 Then
                        oCompany.GetLastError(lErrCode, sErrMsg)
                        MsgBox(sErrMsg)
                    End If
                End If

                Return True

            Catch ex As Exception
                Throw ex
            Finally
                If Not IsNothing(userTableMD) Then
                    System.Runtime.InteropServices.Marshal.ReleaseComObject(userTableMD)
                    userTableMD = Nothing
                    GC.Collect()
                End If
            End Try
        End Function

        Public Shared Function AddSAPUserFields(ByRef oCompany As SAPbobsCOM.Company, ByVal TableName As String, ByVal FieldName As String, ByVal FieldDescription As String,
                ByVal FieldType As SAPbobsCOM.BoFieldTypes,
                Optional ByVal FieldSize As Integer = -1,
                Optional ByVal LinkedTable As String = "",
                Optional ByVal FieldSubType As SAPbobsCOM.BoFldSubTypes = Nothing,
                Optional ByVal validValuesKeys As ArrayList = Nothing,
                Optional ByVal validValuesDescriptions As ArrayList = Nothing,
                Optional ByVal DefValue As String = "",
                Optional ByVal Mandatory As Boolean = False) As Boolean

            ' Tabla en Base de Sap donde se guardan las UserFieldsMD: CUFD
            Dim userFieldMD As SAPbobsCOM.UserFieldsMD
            Dim lResult As Integer
            Dim lErrCode As Integer
            Dim sErrMsg As String = ""


            userFieldMD = Nothing
            userFieldMD = CType(oCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.oUserFields), SAPbobsCOM.UserFieldsMD)

            Try

                If Not Exist_Query(oCompany, TableName, FieldName) Then

                    userFieldMD.TableName = TableName
                    userFieldMD.Name = FieldName
                    userFieldMD.Description = FieldDescription
                    userFieldMD.Type = FieldType
                    If Not IsNothing(FieldSubType) Then userFieldMD.SubType = FieldSubType
                    If FieldSize >= 0 Then userFieldMD.EditSize = FieldSize
                    If DefValue <> "" Then userFieldMD.DefaultValue = DefValue
                    If Not IsNothing(validValuesKeys) AndAlso Not IsNothing(validValuesDescriptions) Then
                        For i As Integer = 0 To validValuesKeys.Count - 1
                            userFieldMD.ValidValues.Value = validValuesKeys(i).ToString
                            userFieldMD.ValidValues.Description = validValuesDescriptions(i).ToString
                            If i <> validValuesKeys.Count - 1 Then
                                userFieldMD.ValidValues.Add()
                            End If
                        Next
                    End If
                    If LinkedTable <> "" Then userFieldMD.LinkedTable = LinkedTable
                    If Mandatory Then userFieldMD.Mandatory = SAPbobsCOM.BoYesNoEnum.tYES

                    lResult = userFieldMD.Add()

                    If lResult = 0 Then
                        Return True
                    Else
                        oCompany.GetLastError(lErrCode, sErrMsg)
                        MsgBox(sErrMsg)
                    End If

                End If

                Return True

            Catch ex As Exception
                Throw ex
            Finally
                If Not IsNothing(userFieldMD) Then
                    System.Runtime.InteropServices.Marshal.ReleaseComObject(userFieldMD)
                    userFieldMD = Nothing
                    GC.Collect()
                End If
            End Try
        End Function

        Public Shared Function Exist_Query(ByRef oCompany As SAPbobsCOM.Company, ByVal TableName As String, ByVal FieldName As String, Optional ByRef FieldID As Integer = 0) As Boolean
            Dim qry As String
            Dim rs As SAPbobsCOM.Recordset

            rs = Nothing
            rs = CType(oCompany.GetBusinessObject(SAPbobsCOM.BoObjectTypes.BoRecordset), SAPbobsCOM.Recordset)

            Try

                qry = " SELECT ""FieldID"" "
                qry += " FROM CUFD "
                qry += " WHERE ""TableID"" = '" + TableName + "' "
                qry += " AND ""AliasID"" = '" + FieldName + "' "

                rs.DoQuery(qry)

                If rs.RecordCount > 0 Then
                    FieldID = CInt(rs.Fields.Item(0).Value)
                    Return True
                End If

                Return False
            Catch ex As Exception
                Throw ex
            Finally
                If Not IsNothing(rs) Then System.Runtime.InteropServices.Marshal.ReleaseComObject(rs)
                rs = Nothing
                GC.Collect()
            End Try
        End Function


    End Class
End Namespace
