'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace InFile
    
    Public Class Menu__mnFacturacion
        Inherits B1XmlFormMenu
        
        Public Sub New()
            MyBase.New
            MenuUID = "mnFacturacion"
            'GENERATED CODE
            Me.LoadXml("frmSOCIO.xml")
        End Sub
        
        <B1Listener(BoEventTypes.et_MENU_CLICK, true)>  _
        Public Overridable Function OnBeforeMenuClick(ByVal pVal As MenuEvent) As Boolean
            'GENERATED CODE
            Me.LoadForm
            Return false
        End Function
    End Class
End Namespace
