'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica

    Public Class Menu__mnSeries
        Inherits B1XmlFormMenu

        Public Sub New()
            MyBase.New
            MenuUID = "mnSeries"
            'GENERATED CODE
            Me.LoadXml("XML\frmSerieFEL.xml")
        End Sub

        <B1Listener(BoEventTypes.et_MENU_CLICK, True)>
        Public Overridable Function OnBeforeMenuClick(ByVal pVal As MenuEvent) As Boolean
            'GENERATED CODE
            Me.LoadForm()

            Try


                Dim oMatrix As SAPbouiCOM.Matrix
                Dim oForm As SAPbouiCOM.Form
                Dim oRecordSet As SAPbobsCOM.Recordset
                Dim sQuery As String = ""
                Dim cell As Cells
                oForm = B1Connections.theAppl.Forms.ActiveForm

                oForm.Freeze(True)



                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select * from ""@SERIESH"" "
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If oRecordSet.RecordCount > 0 Then

                    oForm.Mode = BoFormMode.fm_FIND_MODE
                    oForm.Items.Item("0_U_E").Visible = True
                    oForm.Items.Item("0_U_E").Enabled = True
                    oForm.Items.Item("0_U_E").Specific.value = "1"
                    oForm.Items.Item("1").Click()
                    oForm.Items.Item("1_U_E").Visible = True
                    oForm.Items.Item("1_U_E").Enabled = True
                    oForm.Items.Item("22").Click()
                    oForm.Items.Item("1_U_E").Visible = False
                    oForm.Items.Item("0_U_E").Visible = False

                Else

                    oForm.Items.Item("0_U_E").Specific.value = "1"
                    oForm.Items.Item("1_U_E").Specific.value = "Series SAP"

                    oForm.Items.Item("0_U_E").Visible = False
                    oForm.Items.Item("1_U_E").Visible = False



                End If





                '  
                oMatrix = oForm.Items.Item("22").Specific

                oMatrix.AutoResizeColumns()


                oForm.Freeze(False)






            Catch ex As Exception
                B1Connections.theAppl.SetStatusBarMessage(ex.Message, BoMessageTime.bmt_Medium, True)
            End Try

            Return False
        End Function
    End Class
End Namespace
