'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica

    Public Class Menu__mnDocs
        Inherits B1XmlFormMenu

        Public Sub New()
            MyBase.New
            MenuUID = "mnDocs"
            'GENERATED CODE
            Me.LoadXml("XML\frmEnvio.xml")
        End Sub

        <B1Listener(BoEventTypes.et_MENU_CLICK, True)>
        Public Overridable Function OnBeforeMenuClick(ByVal pVal As MenuEvent) As Boolean
            'GENERATED CODE
            Me.LoadForm()

            Try

                Dim oCombo As SAPbouiCOM.ComboBox
                Dim oForm As SAPbouiCOM.Form
                oForm = B1Connections.theAppl.Forms.ActiveForm

                oForm.Freeze(True)


                oCombo = oForm.Items.Item("20").Specific
                oCombo.ValidValues.Add("", "")
                oCombo.ValidValues.Add("13", "Factura")
                oCombo.ValidValues.Add("14", "Nota De Credito")
                oCombo.ValidValues.Add("DN", "Nota De Debito")
                oCombo.ValidValues.Add("24", "Recibos")


                oForm.Freeze(False)


            Catch ex As Exception
                B1Connections.theAppl.SetStatusBarMessage(ex.Message, BoMessageTime.bmt_Medium, True)
            End Try

            Return False
        End Function
    End Class
End Namespace
