'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica

    Public Class Menu__mnConfiguracion

        Inherits B1XmlFormMenu

    Public Sub New()
        MyBase.New
        MenuUID = "mnConfig"
            'GENERATED CODE
            Me.LoadXml("XML\frmFELCNFG.xml")
        End Sub

    <B1Listener(BoEventTypes.et_MENU_CLICK, True)>
    Public Overridable Function OnBeforeMenuClick(ByVal pVal As MenuEvent) As Boolean

            'GENERATED CODE
            Me.LoadForm()

            Try
                Dim oForm As SAPbouiCOM.Form
                'Dim ComboBox As SAPbouiCOM.ComboBox
                Dim oRecordSet As SAPbobsCOM.Recordset
                Dim sQuery As String = ""


                oForm = B1Connections.theAppl.Forms.ActiveForm




                oForm.Freeze(True)

                oForm.Items.Item("47").Click()
                oForm.Items.Item("0_U_S").Visible = False
                oForm.Items.Item("0_U_E").Visible = False


                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = " Select * from ""@CONFEL"" "
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If oRecordSet.RecordCount > 0 Then
                    oForm.Mode = BoFormMode.fm_FIND_MODE
                    oForm.Items.Item("0_U_E").Visible = True
                    oForm.Items.Item("0_U_E").Enabled = True
                    oForm.Items.Item("0_U_E").Specific.value = "1"
                    oForm.Items.Item("1").Click()
                    oForm.Items.Item("47").Click()
                    oForm.Items.Item("0_U_E").Visible = False

                End If

                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T0.""E_Mail"" from OADM T0"
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If String.IsNullOrEmpty(oRecordSet.Fields.Item(0).Value) Then
                    '    B1Connections.theAppl.SetStatusBarMessage("Configure el Correo Emisor en Detalles Sociedad", BoMessageTime.bmt_Medium, True)
                    'Return False
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure el Correo Emisor en Detalles Sociedad")
                Else
                    oForm.Items.Item("45").Specific.value = oRecordSet.Fields.Item(0).Value
                End If



                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T0.""AliasName"" from OADM T0"
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If String.IsNullOrEmpty(oRecordSet.Fields.Item(0).Value) Then
                    '  B1Connections.theAppl.SetStatusBarMessage("Configure el Nombre Comercial en Detalles Sociedad", BoMessageTime.bmt_Medium, True)
                    'Return False
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure el Nombre Comercial en Detalles Sociedad")
                Else
                    oForm.Items.Item("43").Specific.value = oRecordSet.Fields.Item(0).Value
                End If



                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T0.""TaxIdNum"" from OADM T0"
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If String.IsNullOrEmpty(oRecordSet.Fields.Item(0).Value) Then
                    '  B1Connections.theAppl.SetStatusBarMessage("Configure el NIT en Detalles Sociedad", BoMessageTime.bmt_Medium, True)
                    'Return False
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure el NIT en Detalles Sociedad")
                Else
                    oForm.Items.Item("31").Specific.value = oRecordSet.Fields.Item(0).Value
                End If


                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T0.""Street"" from ADM1 T0"
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If String.IsNullOrEmpty(oRecordSet.Fields.Item(0).Value) Then
                    'B1Connections.theAppl.SetStatusBarMessage("Configure La Direccion en Detalles Sociedad", BoMessageTime.bmt_Medium, True)
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure La Direccion en Detalles Sociedad")

                Else
                    oForm.Items.Item("33").Specific.value = oRecordSet.Fields.Item(0).Value
                End If



                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T0.""PrintHeadr"" from OADM T0"
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If String.IsNullOrEmpty(oRecordSet.Fields.Item(0).Value) Then
                    'B1Connections.theAppl.SetStatusBarMessage("Configure El Nombre De La Razon Social en Detalles Sociedad", BoMessageTime.bmt_Medium, True)
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure El Nombre De La Razon Social en Detalles Sociedad")
                Else
                    oForm.Items.Item("35").Specific.value = oRecordSet.Fields.Item(0).Value
                End If



                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T0.""County"" from ADM1 T0 "
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If String.IsNullOrEmpty(oRecordSet.Fields.Item(0).Value) Then
                    'B1Connections.theAppl.SetStatusBarMessage("Configure El Municipio en Detalles Sociedad", BoMessageTime.bmt_Medium, True)
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure El Municipio en Detalles Sociedad")
                Else
                    oForm.Items.Item("38").Specific.value = oRecordSet.Fields.Item(0).Value
                End If




                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T1.""Name"" from OADM T0 inner join OCST T1 On T0.""State"" = T1.""Code"""
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If String.IsNullOrEmpty(oRecordSet.Fields.Item(0).Value) Then
                    ' B1Connections.theAppl.SetStatusBarMessage("Configure El Departamento en Detalles Sociedad", BoMessageTime.bmt_Medium, True)
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure El Departamento en Detalles Sociedad")
                Else
                    oForm.Items.Item("40").Specific.value = oRecordSet.Fields.Item(0).Value
                End If


                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T0.""Country"" from OADM T0 "
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If String.IsNullOrEmpty(oRecordSet.Fields.Item(0).Value) Then
                    'B1Connections.theAppl.SetStatusBarMessage("Configure El Pais De La Sociedad", BoMessageTime.bmt_Medium, True)
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure El Pais De La Sociedad")
                Else
                    oForm.Items.Item("41").Specific.value = oRecordSet.Fields.Item(0).Value
                End If



                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery = "Select T0.""TaxIdNum"" from OADM T0"
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()

                If oRecordSet.RecordCount = 0 Then
                    'B1Connections.theAppl.MessageBox("ERROR: NO SE HA DEFINIDO UN NIT")
                    oForm.Close()
                    B1Connections.theAppl.MessageBox("Configure El NIT En La Sociedad")

                Else

                    'If Validar_Licencia(oRecordSet.Fields.Item(0).Value.ToString()) = False Then

                    '    B1Connections.theAppl.MessageBox("ERROR: El NIT No Coincide Con La Licencia")
                    '    Exit Try

                    'End If


                End If


                oForm.Freeze(False)
            Catch ex As Exception
                '   B1Connections.theAppl.SetStatusBarMessage(ex.Message, BoMessageTime.bmt_Medium, True)
            End Try


            Return False
        End Function
    End Class
End Namespace
