'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica

    Public Class Matrix__CONFSERIE10__22
        Inherits B1Item

        Public Sub New()
            MyBase.New
            FormType = "CONFSERIE10"
            ItemUID = "22"
        End Sub
        <B1Listener(BoEventTypes.et_CLICK, True)>
        Public Overridable Function OnBeforeClick(ByVal pVal As ItemEvent) As Boolean
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("22")
            Dim matrix As Matrix = CType(item.Specific, Matrix)
            'ADD YOUR ACTION CODE HERE ...

            Dim oRecordSet As SAPbobsCOM.Recordset
            Dim sQuery As String = ""
            'ADD YOUR ACTION CODE HERE ...

            Try

                If pVal.ColUID = "V_1" Then


                    form.Freeze(True)


                    Dim sboMatrix As SAPbouiCOM.Matrix = CType(form.Items.Item("22").Specific, SAPbouiCOM.Matrix)
                    Dim sboCol As SAPbouiCOM.Column = CType(sboMatrix.Columns.Item("V_1"), SAPbouiCOM.Column)

                    While sboCol.ValidValues.Count > 0
                        sboCol.ValidValues.Remove(0, SAPbouiCOM.BoSearchKey.psk_Index)
                    End While


                    oRecordSet = Nothing
                    oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)


                    If matrix.Columns.Item("V_0").Cells.Item(pVal.Row).Specific.Value = "13" Then

                        sQuery = "Select ""Series"",""SeriesName"" from NNM1 where ""ObjectCode"" = '13' and ""DocSubType"" <> 'DN' "

                    ElseIf matrix.Columns.Item("V_0").Cells.Item(pVal.Row).Specific.Value = "DN" Then
                        sQuery = "Select ""Series"",""SeriesName"" from NNM1 where ""ObjectCode"" = '13' and ""DocSubType"" = 'DN' "

                    ElseIf matrix.Columns.Item("V_0").Cells.Item(pVal.Row).Specific.Value = "18" Then
                        sQuery = "Select ""Series"",""SeriesName"" from NNM1 where ""ObjectCode"" = '18' and ""DocSubType"" <> 'DM' "
                    Else
                        sQuery = "Select ""Series"",""SeriesName"" from NNM1 where ""ObjectCode"" = '" & matrix.Columns.Item("V_0").Cells.Item(pVal.Row).Specific.Value & "' "
                    End If



                    oRecordSet.DoQuery(sQuery)
                    oRecordSet.MoveFirst()

                    sboCol.ValidValues.Add("", "")

                    While Not oRecordSet.EoF
                        sboCol.ValidValues.Add(oRecordSet.Fields.Item(0).Value, oRecordSet.Fields.Item(1).Value)
                        oRecordSet.MoveNext()
                    End While


                    matrix.AutoResizeColumns()

                    form.Freeze(False)


                End If


            Catch ex As Exception
                B1Connections.theAppl.SetStatusBarMessage(ex.Message, BoMessageTime.bmt_Medium, True)
            End Try



            Return True
        End Function


        <B1Listener(BoEventTypes.et_LOST_FOCUS, False)>
        Public Overridable Sub OnLostFocus(ByVal pVal As ItemEvent)
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("22")
            Dim sQuery As String
            Dim oRecordSet As SAPbobsCOM.Recordset
            Dim matrix As Matrix = CType(item.Specific, Matrix)
            'ADD YOUR ACTION CODE HERE ...




            If pVal.ColUID = "V_1" Then


                matrix.Columns.Item("V_2").Cells.Item(pVal.Row).Specific.Value = matrix.Columns.Item("V_1").Cells.Item(pVal.Row).Specific.Value


                If matrix.Columns.Item("V_0").Cells.Item(pVal.Row).Specific.Value = "13" Then

                    sQuery = "Select ""SeriesName"" from NNM1 where ""ObjectCode"" = '13' and ""DocSubType"" <> 'DN' and ""Series"" = '" & matrix.Columns.Item("V_2").Cells.Item(pVal.Row).Specific.Value & "' "

                ElseIf matrix.Columns.Item("V_0").Cells.Item(pVal.Row).Specific.Value = "DN" Then
                    sQuery = "Select ""SeriesName"" from NNM1 where ""ObjectCode"" = '13' and ""DocSubType"" = 'DN' and ""Series"" = '" & matrix.Columns.Item("V_2").Cells.Item(pVal.Row).Specific.Value & "' "
                ElseIf matrix.Columns.Item("V_0").Cells.Item(pVal.Row).Specific.Value = "18" Then
                    sQuery = "Select ""SeriesName"" from NNM1 where ""ObjectCode"" = '18' and ""DocSubType"" <> 'DM' and ""Series"" = '" & matrix.Columns.Item("V_2").Cells.Item(pVal.Row).Specific.Value & "' "
                Else
                    sQuery = "Select ""SeriesName"" from NNM1 where ""ObjectCode"" = '" & matrix.Columns.Item("V_0").Cells.Item(pVal.Row).Specific.Value & "' and ""Series"" = '" & matrix.Columns.Item("V_2").Cells.Item(pVal.Row).Specific.Value & "' "
                End If


                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                oRecordSet.DoQuery(sQuery)
                oRecordSet.MoveFirst()


                matrix.Columns.Item("V_3").Cells.Item(pVal.Row).Specific.Value = oRecordSet.Fields.Item(0).Value




                matrix.AutoResizeColumns()

            End If




        End Sub


        <B1Listener(BoEventTypes.et_MATRIX_LOAD, False)>
        Public Overridable Sub OnAfterMatrixLoad(ByVal pVal As ItemEvent)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("22")
            Dim matrix As Matrix = CType(item.Specific, Matrix)


            form.Freeze(True)


            'Dim rows As Int16 = matrix.RowCount


            'For iContLinea As Integer = 1 To rows

            '   matrix.GetLineData(iContLinea)


            'Dim sboCol As SAPbouiCOM.Column = CType(matrix.Columns.Item("V_1"), SAPbouiCOM.Column)
            'sboCol.Editable = False
            'Next



            form.Freeze(False)





        End Sub

    End Class
End Namespace
