'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica
    
    Public Class Button__ftTraslados01__14
        Inherits B1Item
        
        Public Sub New()
            MyBase.New
            FormType = "ftTraslados01"
            ItemUID = "14"
        End Sub

        <B1Listener(BoEventTypes.et_CLICK, False)>
        Public Overridable Sub OnAfterClick(ByVal pVal As ItemEvent)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("14")
            Dim button As Button = CType(item.Specific, Button)
            'ADD YOUR ACTION CODE HERE ...

            item = form.Items.Item("3")
            Dim oMatrix As SAPbouiCOM.Matrix
            oMatrix = CType(item.Specific, Matrix)

            Dim oCheckBoxColumn As SAPbouiCOM.CheckBox

            Try
                form.Freeze(True)

                For iCont As Integer = 1 To oMatrix.RowCount
                    oCheckBoxColumn = CType(oMatrix.Columns.Item("oC01").Cells.Item(iCont).Specific, SAPbouiCOM.CheckBox)

                    oCheckBoxColumn.Checked = False
                Next

                form.Freeze(False)
            Catch ex As Exception

            End Try





        End Sub

    End Class
End Namespace
