'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica
    
    Public Class Button__ftTraslados01__8
        Inherits B1Item
        
        Public Sub New()
            MyBase.New
            FormType = "ftTraslados01"
            ItemUID = "8"
        End Sub

        <B1Listener(BoEventTypes.et_CLICK, False)>
        Public Overridable Sub OnAfterClick(ByVal pVal As ItemEvent)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("8")
            Dim button As Button = CType(item.Specific, Button)
            Dim oCombo As ComboBox
            Dim sDoc As String = ""
            Dim oMatrix As Matrix
            Dim oCheckBoxColumn As CheckBox
            Dim iRespuesta As Integer = 0
            'ADD YOUR ACTION CODE HERE ...

            oMatrix = form.Items.Item("3").Specific
            oCombo = form.Items.Item("20").Specific

            Try


                If oMatrix.RowCount > 0 Then


                    iRespuesta = B1Connections.theAppl.MessageBox("Desea Firmar Estos Documentos", 1, "SI", "NO")


                    If iRespuesta = 1 Then




                        sDoc = oCombo.Value
                        sDoc = sDoc.Trim().TrimEnd().TrimStart()

                        'oProgBar = Nothing
                        'oProgBar = B1Connections.theAppl.StatusBar.CreateProgressBar("Procesando Facturas Pendientes...", oMatrix.RowCount, False)
                        'iContProgBar = 1

                        For iRow As Integer = 1 To oMatrix.RowCount

                            'oProgBar.Value = iContProgBar
                            'iContProgBar = iContProgBar + 1
                            SetFilters()


                            oCheckBoxColumn = CType(oMatrix.Columns.Item("oC01").Cells.Item(iRow).Specific, SAPbouiCOM.CheckBox)


                            If oCheckBoxColumn.Checked = True Then

                                If sDoc = "13" Then

                                    Globales.ProcesoFacturaElectronica("13", oMatrix.Columns.Item("oC10").Cells.Item(iRow).Specific.value, form.Items.Item("1000001").Specific.value)


                                ElseIf (sDoc = "14") Then
                                    Globales.ProcesoFacturaElectronica("14", oMatrix.Columns.Item("oC10").Cells.Item(iRow).Specific.value, form.Items.Item("1000001").Specific.value)
                                ElseIf (sDoc = "DN") Then
                                    Globales.ProcesoFacturaElectronica("DN", oMatrix.Columns.Item("oC10").Cells.Item(iRow).Specific.value, form.Items.Item("1000001").Specific.value)
                                ElseIf (sDoc = "24") Then
                                    Globales.ProcesoFacturaElectronica("24", oMatrix.Columns.Item("oC10").Cells.Item(iRow).Specific.value, form.Items.Item("1000001").Specific.value)
                                End If

                            End If


                        Next

                        'oProgBar.Stop()
                        'If System.Runtime.InteropServices.Marshal.IsComObject(oProgBar) Then System.Runtime.InteropServices.Marshal.ReleaseComObject(oProgBar)
                        'oProgBar = Nothing


                        oMatrix.Clear()



                    End If

                Else

                    B1Connections.theAppl.SetStatusBarMessage("No Hay Documentos Pendientes De Procesar......", BoMessageTime.bmt_Medium, True)

                End If


                form.Items.Item("13").Visible = False
                form.Items.Item("14").Visible = False



            Catch ex As Exception

                'oProgBar.Stop()
                'If System.Runtime.InteropServices.Marshal.IsComObject(oProgBar) Then System.Runtime.InteropServices.Marshal.ReleaseComObject(oProgBar)
                'oProgBar = Nothing

                B1Connections.theAppl.SetStatusBarMessage(ex.Message, BoMessageTime.bmt_Medium, True)

            End Try



        End Sub

    End Class
End Namespace
