'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica
    
    Public Class Button__ftTraslados01__4
        Inherits B1Item
        
        Public Sub New()
            MyBase.New
            FormType = "ftTraslados01"
            ItemUID = "4"
        End Sub

        <B1Listener(BoEventTypes.et_CLICK, False)>
        Public Overridable Sub OnAfterClick(ByVal pVal As ItemEvent)
            Dim ActionSuccess As Boolean = pVal.ActionSuccess
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("4")
            Dim button As Button = CType(item.Specific, Button)
            Dim sQuery As String = ""
            Dim sQuery2 As String = ""
            Dim oRecordSetCnfgFace As Recordset
            Dim oRecordSet As Recordset
            Dim oCombo As ComboBox
            Dim oCombo2 As ComboBox
            Dim Texto1 As String
            Dim Texto2 As String
            Dim oMatrix As Matrix


            'ADD YOUR ACTION CODE HERE ...

            Try


                oRecordSetCnfgFace = Nothing
                oRecordSetCnfgFace = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)
                sQuery2 = "select * from ""@CONFEL"" "
                oRecordSetCnfgFace.DoQuery(sQuery2)
                oRecordSetCnfgFace.MoveFirst()

                oRecordSet = Nothing
                oRecordSet = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)

                oMatrix = form.Items.Item("3").Specific
                oCombo = form.Items.Item("20").Specific
                oCombo2 = form.Items.Item("1000001").Specific

                Texto1 = oCombo.Value
                Texto2 = oCombo2.Value


                Dim oColumns As SAPbouiCOM.Columns = oMatrix.Columns

                form.Freeze(True)
                If oMatrix.Columns.Count > 0 Then
                    oMatrix.Clear()

                    For iContCol As Integer = 0 To oColumns.Count - 1
                        'validaCampo = True

                        oColumns.Remove(0)

                        'validaCampo = False
                    Next




                End If

                form.Freeze(False)

                If oMatrix.Columns.Count <= 0 Then
                    form.Freeze(True)
                    'validaCampo = True
                    Dim oColumn0 As SAPbouiCOM.Column = oColumns.Add("oC00", SAPbouiCOM.BoFormItemTypes.it_EDIT)
                    oColumn0.TitleObject.Caption = ""
                    oColumn0.Editable = True

                    Dim oColumn1 As SAPbouiCOM.Column = oColumns.Add("oC01", SAPbouiCOM.BoFormItemTypes.it_CHECK_BOX)
                    oColumn1.TitleObject.Caption = "T"
                    oColumn1.Editable = True

                    Dim oColumn2 As SAPbouiCOM.Column = oColumns.Add("oC02", SAPbouiCOM.BoFormItemTypes.it_LINKED_BUTTON)
                    oColumn2.TitleObject.Caption = "DocEntry"
                    oColumn2.Editable = False

                    Dim oLink As SAPbouiCOM.LinkedButton = oColumn2.ExtendedObject

                    If Texto1.Trim() = "13" Then
                        oLink.LinkedObject = SAPbouiCOM.BoLinkedObject.lf_Invoice
                        ' validaCampo = True
                    ElseIf Texto1.Trim() = "14" Then
                        oLink.LinkedObject = SAPbouiCOM.BoLinkedObject.lf_InvoiceCreditMemo
                        ' validaCampo = True
                    ElseIf Texto1.Trim() = "DN" Then
                        oLink.LinkedObject = SAPbouiCOM.BoLinkedObject.lf_Invoice
                        ' validaCampo = True
                    End If

                    Dim oColumn3 As SAPbouiCOM.Column = oColumns.Add("oC10", SAPbouiCOM.BoFormItemTypes.it_EDIT)
                    oColumn3.TitleObject.Caption = "#"
                    oColumn3.Editable = False

                    Dim oColumn4 As SAPbouiCOM.Column = oColumns.Add("oC04", SAPbouiCOM.BoFormItemTypes.it_EDIT)
                    oColumn4.TitleObject.Caption = "Nombre Socio De Negocio"
                    oColumn4.Editable = False


                    Dim oColumn9 As SAPbouiCOM.Column = oColumns.Add("oC03", SAPbouiCOM.BoFormItemTypes.it_EDIT)
                    oColumn9.TitleObject.Caption = "Socio De Negocio"
                    oColumn9.Editable = False

                    Dim oColumn5 As SAPbouiCOM.Column = oColumns.Add("oC05", SAPbouiCOM.BoFormItemTypes.it_EDIT)
                    oColumn5.TitleObject.Caption = "Fecha De Contabilización"
                    oColumn5.Editable = False

                    Dim oColumn6 As SAPbouiCOM.Column = oColumns.Add("oC07", SAPbouiCOM.BoFormItemTypes.it_EDIT)
                    oColumn6.TitleObject.Caption = "Mensaje Error"
                    oColumn6.Editable = False

                    Dim oColumn7 As SAPbouiCOM.Column = oColumns.Add("oC08", SAPbouiCOM.BoFormItemTypes.it_EDIT)
                    oColumn7.TitleObject.Caption = "Comentarios"
                    oColumn7.Editable = False

                    Dim oColumn8 As SAPbouiCOM.Column = oColumns.Add("oC09", SAPbouiCOM.BoFormItemTypes.it_EDIT)
                    oColumn8.TitleObject.Caption = "Monto"
                    oColumn8.Editable = False

                    form.Freeze(False)
                End If






                If Texto1.Trim() <> "" And Texto2.Trim() = "" And form.Items.Item("1_U_E").Specific.value = "" And form.Items.Item("2_U_E").Specific.value = "" Then


                    If B1Connections.diCompany.DbServerType = BoDataServerTypes.dst_HANADB Then

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie"" where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""DocSubType"" <> 'DN' and T0.""CANCELED"" = 'N' "
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' "
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""DocSubType"" = 'DN' and T0.""CANCELED"" = 'N' "
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N'"
                        End If

                    Else


                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""DocSubType"" <> 'DN' and T0.""CANCELED"" = 'N'"
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N'"
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""DocSubType"" = 'DN' and T0.""CANCELED"" = 'N'"
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N'"
                        End If


                    End If



                ElseIf Texto1.Trim() <> "" And Texto2.Trim() = "" And form.Items.Item("1_U_E").Specific.value = "" And form.Items.Item("2_U_E").Specific.value = "" Then



                    If B1Connections.diCompany.DbServerType = BoDataServerTypes.dst_HANADB Then

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""DocNum"" = " & form.Items.Item("19").Specific.value
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""DocNum"" = " & form.Items.Item("19").Specific.value
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""DocNum"" = " & form.Items.Item("19").Specific.value
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""DocNum"" = " & form.Items.Item("19").Specific.value
                        End If


                    Else


                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""DocNum"" = " & form.Items.Item("19").Specific.value
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""DocNum"" = " & form.Items.Item("19").Specific.value
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""DocNum"" = " & form.Items.Item("19").Specific.value
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N'  And T0.""DocNum"" = " & form.Items.Item("19").Specific.value
                        End If

                    End If




                ElseIf Texto1.Trim() <> "" And Texto2.Trim() <> "" And form.Items.Item("1_U_E").Specific.value = "" And form.Items.Item("2_U_E").Specific.value = "" Then


                    If B1Connections.diCompany.DbServerType = BoDataServerTypes.dst_HANADB Then

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""Series"" = " & Texto2.Trim()
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""Series"" = " & Texto2.Trim()
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""Series"" = " & Texto2.Trim()
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""Series"" = " & Texto2.Trim()
                        End If

                    Else
                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""Series"" = " & Texto2.Trim()
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""Series"" = " & Texto2.Trim()
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""Series"" = " & Texto2.Trim()
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""Series"" = " & Texto2.Trim()
                        End If
                    End If



                ElseIf Texto1.Trim() <> "" And form.Items.Item("1_U_E").Specific.value <> "" And form.Items.Item("2_U_E").Specific.value <> "" And Texto2.Trim() = "" Then



                    If B1Connections.diCompany.DbServerType = BoDataServerTypes.dst_HANADB Then

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        End If

                    Else

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        End If

                    End If


                ElseIf Texto1.Trim() <> "" And Texto2.Trim() <> "" And form.Items.Item("1_U_E").Specific.value <> "" And form.Items.Item("2_U_E").Specific.value <> "" Then



                    If B1Connections.diCompany.DbServerType = BoDataServerTypes.dst_HANADB Then

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        End If

                    Else

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' "
                        End If

                    End If



                ElseIf Texto1.Trim() <> "" And Texto2.Trim() <> "" And form.Items.Item("1_U_E").Specific.value = "" And form.Items.Item("2_U_E").Specific.value = "" Then


                    If B1Connections.diCompany.DbServerType = BoDataServerTypes.dst_HANADB Then
                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "' "
                        End If
                    Else
                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "' "
                        End If
                    End If



                ElseIf Texto1.Trim() <> "" And Texto2.Trim() <> "" And form.Items.Item("1_U_E").Specific.value <> "" And form.Items.Item("2_U_E").Specific.value <> "" Then


                    If B1Connections.diCompany.DbServerType = BoDataServerTypes.dst_HANADB Then

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where IFNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        End If

                    Else

                        If Texto1.Trim() = "13" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" <> 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "14" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORIN T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "DN" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from OINV T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""CANCELED"" = 'N' and T0.""DocSubType"" = 'DN' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        ElseIf Texto1.Trim() = "24" Then
                            sQuery = "select T0.""DocEntry"" ""No"", T0.""DocNum"" ""Num"",  T0.""CardCode"" ""Socio De Negocios"", T0.""CardName"" ""Nombre"", T0.""DocDate"" ""Fecha de Contabilizacion"", T0.""U_Mensaje"" ""Error"",T0.""Comments"" ""Co"",T0.""DocTotal"" ""Total""  from ORCT T0 inner join ""@SERIESO"" T1 on T0.""Series"" = T1.""U_Serie""  where ISNULL(T0.""U_Valido"",'') = 'false' and T0.""Canceled"" = 'N' And T0.""Series"" = " & Texto2.Trim() & " And T0.""DocDate"" Between '" & form.Items.Item("1_U_E").Specific.value & "' and '" & form.Items.Item("2_U_E").Specific.value & "' And T0.""CardCode"" = '" & form.Items.Item("17").Specific.value & "'"
                        End If


                    End If
                End If



                If Not String.IsNullOrEmpty(sQuery) Then



                    oRecordSet.DoQuery(sQuery)

                    If oRecordSet.RecordCount > 0 Then

                        form.DataSources.DataTables.Add("DATABLE" & IContName)
                        form.DataSources.DataTables.Item("DATABLE" & IContName).Clear()
                        form.DataSources.DataTables.Item("DATABLE" & IContName).ExecuteQuery(sQuery)
                        oMatrix.Columns.Item("oC02").DataBind.Bind("DATABLE" & IContName, "No")
                        oMatrix.Columns.Item("oC10").DataBind.Bind("DATABLE" & IContName, "Num")
                        oMatrix.Columns.Item("oC03").DataBind.Bind("DATABLE" & IContName, "Socio De Negocios")
                        oMatrix.Columns.Item("oC04").DataBind.Bind("DATABLE" & IContName, "Nombre")
                        oMatrix.Columns.Item("oC05").DataBind.Bind("DATABLE" & IContName, "Fecha de Contabilizacion")
                        oMatrix.Columns.Item("oC07").DataBind.Bind("DATABLE" & IContName, "Error")
                        oMatrix.Columns.Item("oC08").DataBind.Bind("DATABLE" & IContName, "Co")
                        oMatrix.Columns.Item("oC09").DataBind.Bind("DATABLE" & IContName, "Total")
                        oMatrix.LoadFromDataSource()
                        oMatrix.AutoResizeColumns()


                        form.Items.Item("13").Visible = True
                        form.Items.Item("14").Visible = True
                    Else

                        form.Items.Item("13").Visible = False
                        form.Items.Item("14").Visible = False
                        oMatrix.Clear()

                        Dim oColumns2 As SAPbouiCOM.Columns = oMatrix.Columns

                        form.Freeze(True)
                        If oMatrix.Columns.Count > 0 Then
                            oMatrix.Clear()

                            For iContCol As Integer = 0 To oColumns2.Count - 1
                                'validaCampo = True

                                oColumns2.Remove(0)

                                'validaCampo = False
                            Next




                        End If

                        form.Freeze(False)

                        B1Connections.theAppl.SetStatusBarMessage("No Hay Registros Pendientes", BoMessageTime.bmt_Medium, False)

                    End If

                    IContName = IContName + 1
                Else

                    B1Connections.theAppl.SetStatusBarMessage("Seleccione un filtro......", BoMessageTime.bmt_Medium, True)

                End If

            Catch ex As Exception
                B1Connections.theAppl.SetStatusBarMessage(ex.Message, BoMessageTime.bmt_Medium, True)
            End Try







        End Sub

    End Class
End Namespace
