'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports B1WizardBase
Imports SAPbobsCOM
Imports SAPbouiCOM

Namespace Factura_Electronica
    
    Public Class ComboBox__ftTraslados01__20
        Inherits B1Item
        
        Public Sub New()
            MyBase.New
            FormType = "ftTraslados01"
            ItemUID = "20"
        End Sub

        <B1Listener(BoEventTypes.et_LOST_FOCUS, False)>
        Public Overridable Sub OnLostFocus(ByVal pVal As ItemEvent)
            Dim form As Form = B1Connections.theAppl.Forms.Item(pVal.FormUID)
            Dim item As Item = form.Items.Item("20")
            Dim combobox As ComboBox = CType(item.Specific, ComboBox)
            Dim oCombo As ComboBox
            Dim oRecordset As Recordset
            Dim sQuery As String
            Dim sResultado As String
            'ADD YOUR ACTION CODE HERE ...


            oCombo = form.Items.Item("1000001").Specific

            While oCombo.ValidValues.Count > 0
                oCombo.ValidValues.Remove(0, SAPbouiCOM.BoSearchKey.psk_Index)
            End While


            oRecordset = Nothing
            oRecordset = B1Connections.diCompany.GetBusinessObject(BoObjectTypes.BoRecordset)

            sResultado = combobox.Value

            If sResultado.Trim().TrimEnd().TrimStart() = "13" Then

                sQuery = "Select ""Series"",""SeriesName"" from NNM1 where ""ObjectCode"" = '13' and ""DocSubType"" <> 'DN' "

            ElseIf sResultado.Trim().TrimEnd().TrimStart() = "DN" Then
                sQuery = "Select ""Series"",""SeriesName"" from NNM1 where ""ObjectCode"" = '13' and ""DocSubType"" = 'DN' "
            Else
                sQuery = "Select ""Series"",""SeriesName"" from NNM1 where ""ObjectCode"" = '" & sResultado.Trim().TrimEnd().TrimStart() & "' "
            End If



            oRecordset.DoQuery(sQuery)
            oRecordset.MoveFirst()

            oCombo.ValidValues.Add("", "")

            While Not oRecordset.EoF
                oCombo.ValidValues.Add(oRecordset.Fields.Item(0).Value, oRecordset.Fields.Item(1).Value)
                oRecordset.MoveNext()
            End While





        End Sub

    End Class
End Namespace
